import React, { createContext, useContext, useState, useEffect } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

export type Language = "en" | "hi" | "te";

export const translations = {
  en: {
    profile: "Profile",
    myPets: "My pets",
    upcomingReminders: "Upcoming Reminders",
    logCare: "Log care",
    quickAccess: "Quick access",
    activity: "Activity",
    signOut: "Sign out",
    language: "Language",
    selectLanguage: "Select Language",
    english: "English",
    hindi: "Hindi",
    telugu: "Telugu",
    settings: "Settings",
    chooseLanguage: "Choose Language",
    cancel: "Cancel",
    addPet: "Add pet",
    medicalRecords: "Medical Records",
    petPassport: "Pet Passport",
    today: "Today",
    events: "Events",
    lostFound: "Lost & Found",
    care: "Care",
    notifications: "Notifications",
    messages: "Messages",
    badgesAchievements: "Badges & Achievements",
    nothingInFeedYet: "Nothing in your feed yet",
    allCaughtUp: "You're all caught up",
    followToFillFeed: "Follow people or post to fill your feed. Want to see what others are sharing?",
    seenAllPosts: "You've seen all posts from people you follow. Want to discover more?",
    showSuggestedPosts: "Show suggested posts",
    suggestedForYou: "Suggested for you",
    yourStory: "Your Story",
    addStory: "Add Story",
    chooseStorySource: "Choose a media source for your story",
    openCamera: "Open Camera",
    chooseFromGallery: "Choose from Gallery",
    permissionRequired: "Permission Required",
    allowGalleryAccess: "Please allow gallery access to share stories.",
    allowCameraAccess: "Please allow camera access to capture stories.",
    videoTooLong: "Video too long",
    selectShorterVideo: "Please select a video shorter than 30 seconds.",
    noPostsYet: "No posts yet",
    shareFirstMoment: "Be the first to share a moment of your pet!",
    selectLocation: "Select Location",
    error: "Error",
    failedToSaveLocation: "Failed to save location.",
    compressing: "Compressing...",
    deletePost: "Delete Post",
    confirmDeletePost: "Are you sure you want to delete this post?",
    delete: "Delete",
    success: "Success",
    postDeletedSuccessfully: "Post deleted successfully.",
    couldNotDeletePost: "Could not delete post.",
    couldNotIdentifyUser: "Could not identify the user to report.",
    failedToSubmitReport: "Failed to submit report.",
    petParent: "Pet parent",
    couldNotPostComment: "Could not post comment.",
    comments: "Comments",
    noCommentsYet: "No comments yet. Start the conversation!",
    addCommentPlaceholder: "Add Comment...",
    post: "Post",
    options: "Options",
    removeFromSaved: "Remove from Saved",
    savePost: "Save Post",
    editPost: "Edit Post",
    aboutThisAccount: "About this Account",
    report: "Report",
    whyReportingPost: "Why are you reporting this post?",
    reportDisclaimer: "Your report is anonymous. If someone is in immediate danger, call the local emergency services - don't wait.",
    thanksFeedback: "Thanks for your feedback",
    reportFeedbackDetail: "We use these reports to show you less of this kind of content in the future.",
    done: "Done",
    noPetsFound: "No Pets Found",
    addPetToProfileBeforeMemory: "Please add a pet to your profile first before adding a memory.",
    failedRetrievePets: "Failed to retrieve your pets.",
    create: "Create",
    newPost: "New Post",
    sharePetPhoto: "Share a photo of your pet",
    askCommunity: "Ask the Community",
    getPetHelp: "Get help from pet parents",
    addMemory: "Add Memory",
    saveToVault: "Save to vault",
    selectPet: "Select Pet",
    reasonDontLikeIt: "I just don't like it",
    reasonBullying: "Bullying or unwanted contact",
    reasonSuicideSelfInjury: "Suicide, self-injury or eating disorders",
    reasonViolenceHate: "Violence, hate or exploitation",
    reasonRestrictedItems: "Selling or promoting restricted items",
    reasonNudity: "Nudity or sexual activity",
    reasonScamSpam: "Scam, fraud or spam",
    reasonFalseInfo: "False information",
    reasonIntellectualProperty: "Intellectual property",
    justNow: "just now",
    minuteAgo: "1 minute ago",
    minutesAgo: "minutes ago",
    hourAgo: "1 hour ago",
    hoursAgo: "hours ago",
    dayAgo: "1 day ago",
    daysAgo: "days ago",
    weekAgo: "1 week ago",
    weeksAgo: "weeks ago",
    monthAgo: "1 month ago",
    monthsAgo: "months ago",
    yearAgo: "1 year ago",
    yearsAgo: "years ago",
    communityTitle: "Circles",
    communitySubtitle: "Conversations that bring pet parents together",
    searchPlaceholder: "Search people, pets, circles, posts…",
    typeToSearch: "Type to search circles, posts, and questions",
    noResultsFor: "No results for",
    tryDifferentKeyword: "Try a different name or keyword",
    follow: "Follow",
    requested: "Requested",
    following: "Following",
    joined: "Joined",
    join: "Join",
    upvotes: "upvotes",
    upvoted: "Upvoted ✓",
    answers: "answers",
    replies: "replies",
    trendingToday: "Trending today",
    noTrendingQuestions: "No trending questions yet. Be the first to ask!",
    yourCircles: "Your circles",
    discoverCircles: "Discover circles",
    notJoinedCircles: "You haven't joined any circles yet. Discover some below!",
    members: "members",
    actionFailed: "Action failed.",
    filterAll: "All",
    filterPeople: "People",
    filterPets: "Pets",
    filterPosts: "Posts",
    filterCircles: "Circles",
    filterQuestions: "Questions",
    filterTags: "#Tags",
    seeAll: "See all",
    lookingForForeverHome: "Looking for a forever home",
    noPetsYet: "No pets yet",
    has: "Has",
    messageOwner: "Message Owner 💬",
    pending: "Pending ⏳",
    declined: "Declined ❌",
    imInterested: "I'm Interested 🐾",
    somethingWentWrong: "Something went wrong",
    couldNotLoadCards: "Couldn't load cards. Check your connection and try again.",
    tryAgain: "Try Again",
    enableBreedMode: "Enable Breed Mode",
    enableBreedModeDesc: "Go to your pet's profile and turn on breeding mode to find matches.",
    addPetFirst: "Add a Pet First",
    addPetFirstDesc: "Add your pet to start finding playdate partners nearby.",
    noMoreCards: "No more cards right now. Check back later.",
    refresh: "Refresh",
    playdateTitle: "Playdate",
    likeStamp: "LIKE",
    nopeStamp: "NOPE",
    itsAMatch: "It's a Match!",
    youAnd: "You and",
    bothSaidYes: "both said yes!",
    startChatting: "Start Chatting",
    keepSwiping: "Keep Swiping",
    discoverTitle: "Discover",
    discoverSubtitle: "Vets, pets & places near you",
    nearbyVets: "Nearby vets",
    addLocation: "Add Location",
    setLocationDesc: "Set your city to find nearby vets",
    findingVetsNear: "Finding vets near",
    noVetsFoundNear: "No veterinarians found nearby in",
    petsNearby: "Pets nearby",
    petsFound: "found",
    modeAll: "All",
    modeAdoption: "Adoption",
    modeFoster: "Foster",
    adoptBadge: "Adopt",
    fosterBadge: "Foster",
    nearby: "Nearby",
    noPetsMatchFilter: "No pets match this filter near you yet.",
    leaveCircleAlertTitle: "Leave Circle",
    leaveCircleAlertMsg: "Leave",
    leave: "Leave",
    failedToLeaveCircle: "Failed to leave circle.",
    deleteCircleAlertTitle: "Delete Circle",
    deleteCircleAlertMsg: "Permanently delete",
    deleteCircleAlertMsg2: "This removes all its discussions and cannot be undone.",
    failedToDeleteCircle: "Failed to delete circle.",
    joinInviteMsg: "Join",
    joinInviteMsg2: "on FurrCircle!",
    circleHeaderTitle: "Circle",
    circleNotFound: "Circle not found",
    inviteMembers: "Invite members",
    joinCircle: "Join Circle",
    discussions: "Discussions",
    ask: "Ask",
    noDiscussionsYet: "No discussions yet. Be the first to ask!",
    byAuthor: "by",
    sendToFriend: "Send to a friend",
    editCircle: "Edit Circle",
    deleteCircle: "Delete Circle",
    leaveCircle: "Leave Circle",
    couldNotLoadEventDetails: "Could not load event details.",
    bookingSuccessTitle: "You're in! 🎉",
    bookingSuccessMsg: "Your spot has been reserved for this event.",
    bookingFailedTitle: "Booking Failed",
    eventDetailsHeaderTitle: "Event Details",
    eventNotFound: "Event not found",
    goingBadge: "✓ GOING",
    eventDateLabel: "Date",
    eventTimeLabel: "Time",
    eventLocationLabel: "Location",
    eventAttendingLabel: "Attending",
    tba: "TBA",
    peopleGoing: "people going",
    aboutEvent: "About",
    goingBtn: "You're Going! 🎉",
    bookRsvpBtn: "Book / RSVP",
    pleaseEnterMedicationName: "Please enter medication name.",
    noPetSelected: "No pet selected.",
    medicationUpdatedSuccessfully: "Medication updated successfully.",
    medicationLoggedSuccessfully: "Medication logged successfully.",
    failedToSaveMedication: "Failed to save medication.",
    editMedicationHeaderTitle: "Edit Medication",
    logMedicationHeaderTitle: "Log Medication",
    medicationNameLabel: "Medication name",
    medicationNamePlaceholder: "e.g. Nexgard",
    medicationDoseLabel: "Dose",
    medicationDosePlaceholder: "e.g. 1 tablet",
    medicationNotesLabel: "Notes",
    medicationNotesPlaceholder: "Any observations…",
    medicationPhotoLabel: "Medication Photo",
    changePhoto: "Change photo",
    addPhoto: "Add photo",
    save: "Save",
    pleaseEnterVaccineName: "Please enter vaccine name.",
    vaccineUpdatedSuccessfully: "Vaccine updated successfully.",
    vaccineLoggedSuccessfully: "Vaccine logged successfully.",
    failedToSaveVaccine: "Failed to save vaccine.",
    editVaccineHeaderTitle: "Edit Vaccine",
    logVaccineHeaderTitle: "Log Vaccine",
    vaccineNameLabel: "Vaccine name",
    vaccineNamePlaceholder: "e.g. DHPP",
    vaccineDateGivenLabel: "Date Given",
    vaccineNextDueDateLabel: "Next due date",
    clear: "Clear",
    selectDateOptional: "Select date (Optional)",
    setReminderNextDueDate: "Set reminder for next due date",
    pleaseEnterAtLeastOneVital: "Please enter at least weight, temperature, or heart rate.",
    pleaseWait: "Please wait",
    stillLoadingPetInfo: "Still loading pet information...",
    invalidTemperatureTitle: "Invalid Temperature",
    invalidTempMsg: "For a {species}, the temperature must be between {min}°C and {max}°C.",
    invalidHeartRateTitle: "Invalid Heart Rate",
    invalidHrMsg: "For a {species}, the heart rate must be between {min} and {max} bpm.",
    vitalsUpdatedSuccessfully: "Vitals updated successfully.",
    vitalsLoggedSuccessfully: "Vitals logged successfully.",
    failedToSaveVitals: "Failed to save vitals.",
    editVitalsHeaderTitle: "Edit Vitals",
    logVitalsHeaderTitle: "Log Vitals",
    weightLabel: "Weight (kg)",
    weightPlaceholder: "e.g. 14.2",
    temperatureLabel: "Temperature (°C)",
    temperaturePlaceholder: "e.g. 38.5",
    normalRange: "Normal range:",
    heartRateLabel: "Heart Rate (bpm)",
    heartRatePlaceholder: "e.g. 80",
    vitalsNotesLabel: "Notes",
    vitalsNotesPlaceholder: "Any observations…",
    fosterAction: "foster",
    adoptAction: "adopt",
    petInterestMessage: "I am interested to {action} your pet named {name}! furrcircle://pet/{id}",
    failedStartConversationOwner: "Failed to start a conversation with the owner.",
    petProfileHeaderTitle: "Pet Profile",
    petNotFound: "Pet not found.",
    unknownBreed: "Unknown breed",
    years: "years",
    noBioAvailable: "No bio available.",
    unknownLocation: "Unknown",
    verified: "Verified",
    ageLabel: "Age",
    weightStatLabel: "Weight",
    cityLabel: "City",
    personalitySectionTitle: "Personality",
    noTraitsSpecified: "No traits specified.",
    gallerySectionTitle: "Gallery",
    noMemory: "No memory",
    noPhoto: "No Photo",
    messageOwnerBtn: "Message owner",
    ok: "OK",
    parent: "parent",
    failedToLoadPost: "Failed to load post.",
    postHeaderTitle: "Post",
    postNotFound: "Post not found.",
    noCommentsBeFirst: "No comments yet. Be first!",
    minShort: "m",
    hourShort: "h",
    dayShort: "d",
    ago: "ago",
    deleteQuestion: "Delete Question",
    confirmDeleteQuestion: "Delete this question and all its answers? This cannot be undone.",
    failedToDelete: "Failed to delete.",
    failedToPostAnswer: "Failed to post answer.",
    questionFallbackTitle: "Question",
    someone: "Someone",
    discussionHeaderTitle: "Discussion",
    vetDisclaimer: "Community advice is not a substitute for a vet. For emergencies, find care now.",
    noAnswersBeFirst: "No answers yet — be first!",
    answersCountOne: "1 answer",
    answersCountMany: "{count} answers",
    member: "Member",
    addAnswerPlaceholder: "Add an answer…",
    postBtnLabel: "Post",
    askedBy: "Asked by",
    postsLabel: "Posts",
    followersLabel: "Followers",
    followingLabel: "Following",
    editProfile: "Edit profile",
    messageLabel: "Message",
    blockUserTitle: "Block @{username}?",
    blockUserDesc: "They won't be able to see your profile or contact you. They won't be notified that you blocked them.",
    blockAction: "Block",
    unblockAction: "Unblock",
    failedToBlockUser: "Failed to block user",
    failedToUnblockUser: "Failed to unblock user",
    couldNotIdentifyUserReport: "Could not identify the user to report.",
    accountNotAvailable: "This account is not available",
    blockedUserMessage: "You've blocked @{username}. Unblock to see their profile.",
    cantViewProfile: "You can't view this profile.",
    accountIsPrivate: "This account is private",
    followToSeePosts: "Follow this account to see their posts.",
    
    noSavedPostsYet: "No saved posts yet.",
    blockUserLabel: "Block @{username}",
    whyReportingUser: "Why are you reporting this user?",
    pets: "Pets",
    saved: "Saved",
    notFollowingAnyoneYet: "Not following anyone yet",
    noFollowersYet: "No followers yet",
    vetDetailsHeaderTitle: "Vet Details",
    phoneUnavailableTitle: "Phone unavailable",
    phoneUnavailableMsg: "This clinic does not have a phone number listed.",
    callClinicTitle: "Call Clinic",
    callClinicMsg: "Call {name} at {phone}.",
    couldNotOpenMaps: "Could not open maps",
    clinicNotFound: "Clinic not found",
    vetClinicFallback: "Veterinary Clinic",
    ratingSuffix: "Rating",
    openLabel: "Open",
    openInMaps: "Open in Maps",
    hoursLabel: "Hours",
    setReminder: "Set Reminder",
    locationLabel: "Location",
    contactLabel: "Contact",
    errorTitle: "Error",
    pleaseSelectPet: "Please select a pet",
    pleaseEnterReasonVisit: "Please enter a reason for the visit",
    invalidVet: "Invalid Vet",
    successTitle: "Success",
    appointmentReminderSet: "Appointment reminder set!",
    errorBookingAppointment: "Error booking appointment",
    bookAppointmentHeaderTitle: "Book Appointment",
    reasonForVisitLabel: "Reason for visit",
    reasonForVisitPlaceholder: "e.g. Annual vaccination",
    confirmBooking: "Confirm Booking",
    bookingProgress: "Booking…",
    vetAppointmentReminderTitle: "Vet Appointment",
    reasonColonLabel: "Reason: {reason}",
    dateLabel: "Date",
    timeLabel: "Time",
    sortDefault: "Default",
    sortAlphaAsc: "A → Z",
    sortAlphaDesc: "Z → A",
    sortRating: "Top Rated",
    sortDistance: "Nearest First",
    sortLabel: "Sort",
    nearbyVetsHeaderTitle: "Nearby Vets",
    searchClinicsPlaceholder: "Search clinics or city...",
    kmAway: "{distance} km away",
    locationNotSetTitle: "Location not set",
    locationNotSetDesc: "Please set your home city to see nearby vets.",
    addLocationBtn: "Add Location",
    noVetsFound: "No vets found",
    noVetsFoundDesc: "Try a different search or sort",
    generalCategory: "General",
    vetAppointmentTitleWithClinic: "Vet Appointment - {name}",
    pleaseEnterReminderTitle: "Please enter a reminder title",
    invalidDateTimeTitle: "Invalid Date/Time",
    invalidDateTimeMsg: "You cannot set a reminder for a date and time that has already passed. Please select a future time.",
    reminderUpdatedSuccess: "Reminder updated successfully!",
    reminderSetSuccess: "Reminder set successfully!",
    errorSavingReminder: "Error saving reminder",
    reminderTypeVaccination: "Vaccination",
    reminderTypeMedication: "Medication",
    reminderTypeGrooming: "Grooming",
    reminderTypeOther: "Other",
    editReminderHeaderTitle: "Edit Reminder",
    setReminderHeaderTitle: "Set Reminder",
    reminderTitleLabel: "Reminder Title",
    reminderTitlePlaceholder: "e.g. Vet checkup appointment",
    reminderTypeLabel: "Reminder Type",
    selectTypePlaceholder: "Select Type",
    notesReasonLabel: "Notes / Reason",
    notesReasonPlaceholder: "Add details, prep instructions, etc.",
    savingChangesProgress: "Saving Changes…",
    saveChangesBtn: "Save Changes",
    aboutAccountHeaderTitle: "About this account",
    aboutAccountIntroText: "To help keep our community authentic, we're showing information about profiles on FurrCircle.",
    dateJoinedLabel: "Date joined",
    accountBasedInLabel: "Account based in",
    july2015Fallback: "July 2015",
    indiaFallback: "India",
    categoryDogs: "Dogs",
    categoryCats: "Cats",
    categoryRescue: "Rescue",
    categoryHealth: "Health",
    categoryTraining: "Training",
    permissionRequiredTitle: "Permission Required",
    galleryPermissionDesc: "Gallery access is required to upload a cover image.",
    requiredTitle: "Required",
    pleaseEnterCircleName: "Please enter a circle name.",
    errorCreatingCircleTitle: "Error creating circle",
    failedToCreateCircleMsg: "Failed to create circle.",
    createCircleHeaderTitle: "Create a Circle",
    coverImageLabel: "Cover Image",
    changeCoverPhotoBtn: "Change Cover Photo",
    tapToAddCoverPhotoPlaceholder: "Tap to add cover photo (optional)",
    nameLabel: "Name",
    circleNamePlaceholder: "e.g. Beagle Buddies",
    descriptionLabel: "Description",
    circleDescPlaceholder: "What is this circle about?",
    categoryLabel: "Category",
    createCircleBtn: "Create Circle",
    personalityFriendly: "Friendly",
    personalityPlayful: "Playful",
    personalityCalm: "Calm",
    personalityActive: "Active",
    personalityIndependent: "Independent",
    personalityCuddly: "Cuddly",
    personalityProtective: "Protective",
    personalityCurious: "Curious",
    speciesDog: "Dog",
    speciesCat: "Cat",
    speciesRabbit: "Rabbit",
    speciesHorse: "Horse",
    speciesPigeon: "Pigeon",
    speciesGoat: "Goat",
    speciesCow: "Cow",
    speciesOther: "Other",
    permissionDeniedTitle: "Permission denied",
    allowLocationAccessSettings: "Allow location access in device settings.",
    failedToFetchLocation: "Failed to fetch location.",
    pleaseEnterPetName: "Please enter your pet's name.",
    pleaseSelectPetSpecies: "Please select or enter your pet's species.",
    pleaseEnterPetBreed: "Please enter your pet's breed.",
    pleaseSelectPetDOB: "Please select your pet's Date of Birth.",
    errorAddingPetTitle: "Error adding pet",
    monthsShort: "{months} mo",
    lessThanOneMonth: "< 1 mo",
    addPetHeaderTitle: "Add a pet",
    changePhotoBtn: "Change photo",
    addPhotoBtn: "Add photo",
    petNamePlaceholder: "e.g. Moona",
    speciesLabel: "Species",
    selectSpeciesPlaceholder: "Select Species",
    customSpeciesLabel: "Custom Species",
    customSpeciesPlaceholder: "Enter species type",
    breedLabel: "Breed",
    breedPlaceholder: "e.g. Border Collie",
    // weightLabel: "Weight",
    // weightPlaceholder: "e.g. 12",
    genderLabel: "Gender",
    femaleGenderOption: "♀ Female",
    maleGenderOption: "♂ Male",
    dateOfBirthLabel: "Date of Birth",
    selectDateOfBirthPlaceholder: "Select Date of Birth",
    microchipIdLabel: "Microchip ID",
    microchipIdPlaceholder: "e.g. 981020000345119",
    personalityLabel: "Personality",
    savingProgress: "Saving…",
    addPetBtn: "Add pet",
    pleaseWriteQuestionFirst: "Please write your question first.",
    failedToPostQuestionMsg: "Failed to post question.",
    askCommunityHeaderTitle: "Ask the Community",
    circleOptionalLabel: "Circle (optional)",
    globalCircleOption: "Global",
    questionLabel: "Question",
    questionPlaceholder: "What's your question?",
    detailsOptionalLabel: "Details (optional)",
    shareMoreContextPlaceholder: "Share more context…",
    tagsOptionalLabel: "Tags (optional, comma-separated)",
    tagsPlaceholder: "health, nutrition, training",
    postQuestionBtn: "Post question",
    todayCelebration: "Today! 🎉",
    tomorrowCelebration: "Tomorrow!",
    inDaysCelebration: "In {days} days",
    turningYearOld: "Turning {age} year old",
    turningYearsOld: "Turning {age} years old",
    petBirthdaysHeaderTitle: "Pet Birthdays",
    upcomingCelebrationsTitle: "Upcoming Celebrations",
    upcomingCelebrationsSub: "Track and prepare for your furry friends' special days!",
    noBirthdaysFoundTitle: "No birthdays found",
    noBirthdaysFoundSub: "Make sure you have added your pets and set their Date of Birth! You can edit your pet profiles to add their birthdays.",
    unblockUserTitle: "Unblock @{username}?",
    unblockUserSub: "They will be able to see your profile and contact you again.",
    unblockActionBtn: "Unblock",
    failedToUnblockMsg: "Failed to unblock user.",
    blockedAccountsHeaderTitle: "Blocked Accounts",
    noBlockedAccountsTitle: "No blocked accounts",
    noBlockedAccountsSub: "Users you block will appear here. You can unblock them at any time.",
    blockedAccountsCountSingle: "{count} blocked account",
    blockedAccountsCountPlural: "{count} blocked accounts",
    unblockBtnLabel: "Unblock",
    monShort: "Mon",
    tueShort: "Tue",
    wedShort: "Wed",
    thuShort: "Thu",
    friShort: "Fri",
    satShort: "Sat",
    sunShort: "Sun",
    // bookAppointmentHeaderTitle: "Book Appointment",
    vetCardShortInfo: "General · Surgery · Open now",
    selectDateLabel: "Select date",
    selectTimeLabel: "Select time",
    confirmAppointmentBtn: "Confirm appointment",
    bookAVetLabel: "Book a Vet",
    logVaccineLabel: "Log Vaccine",
    logVitalsLabel: "Log Vitals",
    logMedsLabel: "Log Meds",
    careAndHealthHeaderTitle: "Care & Health",
    reminderLabel: "Reminder",
    monthlyCheckupDueMsg: "Monthly checkup is due this week",
    bookNowBtn: "Book now",
    careServicesLabel: "Care services",
    medicalRecordsTile: "Medical Records",
    petPassportTile: "Pet Passport",
    whosePassportQuestion: "Whose passport?",
    whichPetQuestion: "Which pet?",
    selectPetPassportSub: "Select a pet to view their passport",
    selectPetRecordsSub: "Select a pet to view health records",
    yearsShort: "{years}y",
  },
  hi: {
    profile: "प्रोफ़ाइल",
    myPets: "मेरे पालतू जानवर",
    upcomingReminders: "आगामी अनुस्मारक",
    logCare: "देखभाल लॉग करें",
    quickAccess: "त्वरित पहुँच",
    activity: "गतिविधि",
    signOut: "साइन आउट",
    language: "भाषा",
    selectLanguage: "भाषा चुनें",
    english: "अंग्रेजी (English)",
    hindi: "हिन्दी (Hindi)",
    telugu: "तेलुगु (Telugu)",
    settings: "सेटिंग्स",
    chooseLanguage: "भाषा चुनें",
    cancel: "रद्द करें",
    addPet: "पालतू जोड़ें",
    medicalRecords: "चिकित्सा रिकॉर्ड",
    petPassport: "पेट पासपोर्ट",
    today: "आज",
    events: "कार्यक्रम",
    lostFound: "खोया-पाया",
    care: "देखभाल",
    notifications: "सूचनाएं",
    messages: "संदेश",
    badgesAchievements: "बैज और उपलब्धियां",
    nothingInFeedYet: "आपके फ़ीड में अभी कुछ नहीं है",
    allCaughtUp: "आप पूरी तरह से अपडेट हैं",
    followToFillFeed: "फ़ीड भरने के लिए लोगों को फ़ॉलो करें या पोस्ट करें। क्या आप देखना चाहते हैं कि अन्य लोग क्या साझा कर रहे हैं?",
    seenAllPosts: "आपने उन सभी लोगों के पोस्ट देख लिए हैं जिन्हें आप फ़ॉलो करते हैं। क्या आप कुछ नया खोजना चाहते हैं?",
    showSuggestedPosts: "सुझाए गए पोस्ट दिखाएं",
    suggestedForYou: "आपके लिए सुझाव",
    yourStory: "आपकी कहानी",
    addStory: "कहानी जोड़ें",
    chooseStorySource: "अपनी कहानी के लिए मीडिया स्रोत चुनें",
    openCamera: "कैमरा खोलें",
    chooseFromGallery: "गैलरी से चुनें",
    permissionRequired: "अनुमति आवश्यक है",
    allowGalleryAccess: "कहानियां साझा करने के लिए कृपया गैलरी एक्सेस की अनुमति दें।",
    allowCameraAccess: "कहानियां कैप्चर करने के लिए कृपया कैमरा एक्सेस की अनुमति दें।",
    videoTooLong: "वीडियो बहुत लंबा है",
    selectShorterVideo: "कृपया 30 सेकंड से छोटा वीडियो चुनें।",
    noPostsYet: "अभी तक कोई पोस्ट नहीं है",
    shareFirstMoment: "अपने पालतू जानवर का पहला पल साझा करने वाले पहले व्यक्ति बनें!",
    selectLocation: "स्थान चुनें",
    error: "त्रुटि",
    failedToSaveLocation: "स्थान सहेजने में विफल।",
    compressing: "कंप्रेस हो रहा है...",
    deletePost: "POST हटाएं",
    confirmDeletePost: "क्या आप वाकई इस पोस्ट को हटाना चाहते हैं?",
    delete: "हटाएं",
    success: "सफलता",
    postDeletedSuccessfully: "पोस्ट सफलतापूर्वक हटा दी गई।",
    couldNotDeletePost: "पोस्ट नहीं हटाई जा सकी।",
    couldNotIdentifyUser: "रिपोर्ट करने के लिए उपयोगकर्ता की पहचान नहीं की जा सकी।",
    failedToSubmitReport: "रिपोर्ट सबमिट करने में विफल।",
    petParent: "पालतू माता-पिता",
    couldNotPostComment: "टिप्पणी पोस्ट नहीं की जा सकी।",
    comments: "टिप्पणियाँ",
    noCommentsYet: "अभी तक कोई टिप्पणी नहीं है। बातचीत शुरू करें!",
    addCommentPlaceholder: "टिप्पणी जोड़ें...",
    post: "पोस्ट",
    options: "विकल्प",
    removeFromSaved: "सेजे गए से निकालें",
    savePost: "पोस्ट सहेजें",
    editPost: "पोस्ट संपादित करें",
    aboutThisAccount: "इस खाते के बारे में",
    report: "रिपोर्ट करें",
    whyReportingPost: "आप इस पोस्ट की रिपोर्ट क्यों कर रहे हैं?",
    reportDisclaimer: "आपकी रिपोर्ट अनाम है। यदि कोई तत्काल खतरे में है, तो स्थानीय आपातकालीन सेवाओं को कॉल करें - प्रतीक्षा न करें।",
    thanksFeedback: "आपकी प्रतिक्रिया के लिए धन्यवाद",
    reportFeedbackDetail: "भविष्य में आपको इस तरह की सामग्री कम दिखाने के लिए हम इन रिपोर्टों का उपयोग करते हैं।",
    done: "हो गया",
    noPetsFound: "कोई पालतू जानवर नहीं मिला",
    addPetToProfileBeforeMemory: "कृपया कोई मेमोरी जोड़ने से पहले अपने प्रोफ़ाइल में एक पालतू जानवर जोड़ें।",
    failedRetrievePets: "आपके पालतू जानवरों को प्राप्त करने में विफल।",
    create: "बनाएं",
    newPost: "नया पोस्ट",
    sharePetPhoto: "अपने पालतू जानवर की एक तस्वीर साझा करें",
    askCommunity: "कम्युनिटी से पूछें",
    getPetHelp: "पालतू माता-पिता से सहायता प्राप्त करें",
    addMemory: "मेमोरी जोड़ें",
    saveToVault: "तिजोरी में सहेजें",
    selectPet: "पालतू जानवर चुनें",
    reasonDontLikeIt: "मुझे यह पसंद नहीं है",
    reasonBullying: "धमकाना या अवांछित संपर्क",
    reasonSuicideSelfInjury: "आत्महत्या, आत्म-चोट या खाने के विकार",
    reasonViolenceHate: "हिंसा, नफरत या शोषण",
    reasonRestrictedItems: "प्रतिबंधित वस्तुओं को बेचना या बढ़ावा देना",
    reasonNudity: "नग्नता या यौन गतिविधि",
    reasonScamSpam: "घोटाला, धोखाधड़ी या स्पैम",
    reasonFalseInfo: "झूठी जानकारी",
    reasonIntellectualProperty: "बौद्धिक संपदा",
    justNow: "अभी-अभी",
    minuteAgo: "1 मिनट पहले",
    minutesAgo: "मिनट पहले",
    hourAgo: "1 घंटा पहले",
    hoursAgo: "घंटे पहले",
    dayAgo: "1 दिन पहले",
    daysAgo: "दिन पहले",
    weekAgo: "1 सप्ताह पहले",
    weeksAgo: "सप्ताह पहले",
    monthAgo: "1 महीना पहले",
    monthsAgo: "महीने पहले",
    yearAgo: "1 वर्ष पहले",
    yearsAgo: "वर्ष पहले",
    communityTitle: "सर्कल",
    communitySubtitle: "बातचीत जो पालतू जानवरों के माता-पिता को एक साथ लाती है",
    searchPlaceholder: "लोग, पालतू जानवर, सर्कल, पोस्ट खोजें…",
    typeToSearch: "सर्कल, पोस्ट और प्रश्न खोजने के लिए टाइप करें",
    noResultsFor: "कोई परिणाम नहीं",
    tryDifferentKeyword: "कोई अन्य नाम या कीवर्ड आज़माएं",
    follow: "फ़ॉलो करें",
    requested: "अनुरोध किया गया",
    following: "फ़ॉलो कर रहे हैं",
    joined: "शामिल",
    join: "शामिल हों",
    upvotes: "अपवोट",
    upvoted: "अपवोट किया गया ✓",
    answers: "उत्तर",
    replies: "जवाब",
    trendingToday: "आज का ट्रेंडिंग",
    noTrendingQuestions: "अभी तक कोई ट्रेंडिंग प्रश्न नहीं हैं। पूछने वाले पहले व्यक्ति बनें!",
    yourCircles: "आपके सर्कल",
    discoverCircles: "सर्कल खोजें",
    notJoinedCircles: "आप अभी तक किसी भी सर्कल में शामिल नहीं हुए हैं। नीचे कुछ खोजें!",
    members: "सदस्य",
    actionFailed: "कार्य विफल रहा।",
    filterAll: "सभी",
    filterPeople: "लोग",
    filterPets: "पालतू जानवर",
    filterPosts: "पोस्ट",
    filterCircles: "सर्कल",
    filterQuestions: "प्रश्न",
    filterTags: "#टैग",
    seeAll: "सभी देखें",
    lookingForForeverHome: "हमेशा के लिए घर की तलाश है",
    noPetsYet: "अभी तक कोई पालतू जानवर नहीं है",
    has: "के पास है",
    messageOwner: "मालिक को संदेश भेजें 💬",
    pending: "लंबित ⏳",
    declined: "अस्वीकृत ❌",
    imInterested: "मुझे दिलचस्पी है 🐾",
    somethingWentWrong: "कुछ गलत हो गया",
    couldNotLoadCards: "कार्ड लोड नहीं हो सके। अपना कनेक्शन जांचें और पुन: प्रयास करें।",
    tryAgain: "पुनः प्रयास करें",
    enableBreedMode: "ब्रीड मोड सक्षम करें",
    enableBreedModeDesc: "मैच खोजने के लिए अपने पालतू जानवर की प्रोफ़ाइल पर जाएं और ब्रीडिंग मोड चालू करें।",
    addPetFirst: "पहले एक पालतू जानवर जोड़ें",
    addPetFirstDesc: "आस-पास खेलने के साथी ढूंढना शुरू करने के लिए अपने पालतू जानवर को जोड़ें।",
    noMoreCards: "अभी और कार्ड नहीं हैं। बाद में वापस आएं।",
    refresh: "रीफ्रेश करें",
    playdateTitle: "प्लेडेट",
    likeStamp: "पसंद",
    nopeStamp: "नहीं",
    itsAMatch: "मैच हो गया!",
    youAnd: "आप और",
    bothSaidYes: "दोनों ने हाँ कहा!",
    startChatting: "बातचीत शुरू करें",
    keepSwiping: "स्वाइप करते रहें",
    discoverTitle: "खोजें",
    discoverSubtitle: "आपके आस-पास के पशु चिकित्सक, पालतू जानवर और स्थान",
    nearbyVets: "आस-पास के पशु चिकित्सक",
    addLocation: "स्थान जोड़ें",
    setLocationDesc: "आस-पास के पशु चिकित्सकों को खोजने के लिए अपना शहर सेट करें",
    findingVetsNear: "के पास पशु चिकित्सक ढूँढना",
    noVetsFoundNear: "में आस-पास कोई पशु चिकित्सक नहीं मिला",
    petsNearby: "आस-पास के पालतू जानवर",
    petsFound: "मिले",
    modeAll: "सभी",
    modeAdoption: "गोद लेना",
    modeFoster: "फॉस्टर",
    adoptBadge: "गोद लें",
    fosterBadge: "फॉस्टर",
    nearby: "आस-पास",
    noPetsMatchFilter: "आपके आस-पास इस फ़िल्टर से मेल खाने वाला कोई पालतू जानवर नहीं है।",
    leaveCircleAlertTitle: "सर्कल छोड़ें",
    leaveCircleAlertMsg: "क्या आप वाकई छोड़ना चाहते हैं",
    leave: "छोड़ें",
    failedToLeaveCircle: "सर्कल छोड़ने में विफल।",
    deleteCircleAlertTitle: "सर्कल हटाएं",
    deleteCircleAlertMsg: "स्थायी रूप से हटाएं",
    deleteCircleAlertMsg2: "यह इसकी सभी चर्चाओं को हटा देता है और इसे पूर्ववत नहीं किया जा सकता है।",
    failedToDeleteCircle: "सर्कल हटाने में विफल।",
    joinInviteMsg: "शामिल हों",
    joinInviteMsg2: "FurrCircle पर!",
    circleHeaderTitle: "सर्कल",
    circleNotFound: "सर्कल नहीं मिला",
    inviteMembers: "सदस्यों को आमंत्रित करें",
    joinCircle: "सर्कल में शामिल हों",
    discussions: "चर्चाएँ",
    ask: "पूछें",
    noDiscussionsYet: "अभी तक कोई चर्चा नहीं। पूछने वाले पहले व्यक्ति बनें!",
    byAuthor: "द्वारा",
    sendToFriend: "मित्र को भेजें",
    editCircle: "सर्कल संपादित करें",
    deleteCircle: "सर्कल हटाएं",
    leaveCircle: "सर्कल छोड़ें",
    couldNotLoadEventDetails: "इवेंट विवरण लोड नहीं किया जा सका।",
    bookingSuccessTitle: "आप शामिल हो गए हैं! 🎉",
    bookingSuccessMsg: "इस इवेंट के लिए आपका स्थान सुरक्षित कर लिया गया है।",
    bookingFailedTitle: "बुकिंग विफल",
    eventDetailsHeaderTitle: "इवेंट विवरण",
    eventNotFound: "इवेंट नहीं मिला",
    goingBadge: "✓ जा रहे हैं",
    eventDateLabel: "दिनांक",
    eventTimeLabel: "समय",
    eventLocationLabel: "स्थान",
    eventAttendingLabel: "उपस्थिति",
    tba: "घोषणा की जाएगी",
    peopleGoing: "लोग जा रहे हैं",
    aboutEvent: "विवरण",
    goingBtn: "आप जा रहे हैं! 🎉",
    bookRsvpBtn: "बुक करें / RSVP",
    pleaseEnterMedicationName: "कृपया दवा का नाम दर्ज करें।",
    noPetSelected: "कोई पालतू जानवर नहीं चुना गया।",
    medicationUpdatedSuccessfully: "दवा सफलतापूर्वक अपडेट की गई।",
    medicationLoggedSuccessfully: "दवा सफलतापूर्वक लॉग की गई।",
    failedToSaveMedication: "दवा सहेजने में विफल।",
    editMedicationHeaderTitle: "दवा संपादित करें",
    logMedicationHeaderTitle: "दवा लॉग करें",
    medicationNameLabel: "दवा का नाम",
    medicationNamePlaceholder: "उदा. नेक्सगार्ड",
    medicationDoseLabel: "खुराक",
    medicationDosePlaceholder: "उदा. 1 खुराक",
    medicationNotesLabel: "टिप्पणियाँ",
    medicationNotesPlaceholder: "कोई भी अवलोकन…",
    medicationPhotoLabel: "दवा की फोटो",
    changePhoto: "फोटो बदलें",
    addPhoto: "फोटो जोड़ें",
    save: "सहेजें",
    pleaseEnterVaccineName: "कृपया वैक्सीन का नाम दर्ज करें।",
    vaccineUpdatedSuccessfully: "वैक्सीन सफलतापूर्वक अपडेट की गई।",
    vaccineLoggedSuccessfully: "वैक्सीन सफलतापूर्वक लॉग की गई।",
    failedToSaveVaccine: "वैक्सीन सहेजने में विफल।",
    editVaccineHeaderTitle: "वैक्सीन संपादित करें",
    logVaccineHeaderTitle: "वैक्सीन लॉग करें",
    vaccineNameLabel: "वैक्सीन का नाम",
    vaccineNamePlaceholder: "उदा. डीएचपीपी",
    vaccineDateGivenLabel: "दी गई तारीख",
    vaccineNextDueDateLabel: "अगली देय तिथि",
    clear: "साफ़ करें",
    selectDateOptional: "तारीख चुनें (वैकल्पिक)",
    setReminderNextDueDate: "अगली देय तिथि के लिए अनुस्मारक सेट करें",
    pleaseEnterAtLeastOneVital: "कृपया कम से कम वजन, तापमान या हृदय गति दर्ज करें।",
    pleaseWait: "कृपया प्रतीक्षा करें",
    stillLoadingPetInfo: "अभी भी पालतू जानवर की जानकारी लोड हो रही है...",
    invalidTemperatureTitle: "अमान्य तापमान",
    invalidTempMsg: "{species} के लिए, तापमान {min}°C और {max}°C के बीच होना चाहिए।",
    invalidHeartRateTitle: "अमान्य हृदय गति",
    invalidHrMsg: "{species} के लिए, हृदय गति {min} और {max} bpm के बीच होनी चाहिए।",
    vitalsUpdatedSuccessfully: "महत्वपूर्ण संकेत सफलतापूर्वक अपडेट किए गए।",
    vitalsLoggedSuccessfully: "महत्वपूर्ण संकेत सफलतापूर्वक लॉग किए गए।",
    failedToSaveVitals: "महत्वपूर्ण संकेत सहेजने में विफल।",
    editVitalsHeaderTitle: "महत्वपूर्ण संकेत संपादित करें",
    logVitalsHeaderTitle: "महत्वपूर्ण संकेत लॉग करें",
    weightLabel: "वजन (किलोग्राम)",
    weightPlaceholder: "उदा. 14.2",
    temperatureLabel: "तापमान (°C)",
    temperaturePlaceholder: "उदा. 38.5",
    normalRange: "सामान्य सीमा:",
    heartRateLabel: "हृदय गति (bpm)",
    heartRatePlaceholder: "उदा. 80",
    vitalsNotesLabel: "टिप्पणियाँ",
    vitalsNotesPlaceholder: "कोई भी अवलोकन…",
    fosterAction: "फॉस्टर",
    adoptAction: "गोद लेना",
    petInterestMessage: "मैं आपके {name} नाम के पालतू जानवर को {action} करने में रुचि रखता हूँ! furrcircle://pet/{id}",
    failedStartConversationOwner: "मालिक के साथ बातचीत शुरू करने में विफल।",
    petProfileHeaderTitle: "पालतू जानवर की प्रोफ़ाइल",
    petNotFound: "पालतू जानवर नहीं मिला।",
    unknownBreed: "अज्ञात नस्ल",
    years: "वर्ष",
    noBioAvailable: "कोई जीवनी उपलब्ध नहीं है।",
    unknownLocation: "अज्ञात",
    verified: "सत्यापित",
    ageLabel: "उम्र",
    weightStatLabel: "वजन",
    cityLabel: "शहर",
    personalitySectionTitle: "व्यक्तित्व",
    noTraitsSpecified: "कोई लक्षण निर्दिष्ट नहीं हैं।",
    gallerySectionTitle: "गैलरी",
    noMemory: "कोई मेमोरी नहीं",
    noPhoto: "कोई फोटो नहीं",
    messageOwnerBtn: "मालिक को संदेश भेजें",
    ok: "ठीक है",
    parent: "पैरेंट",
    failedToLoadPost: "पोस्ट लोड करने में विफल।",
    postHeaderTitle: "पोस्ट",
    postNotFound: "पोस्ट नहीं मिली।",
    noCommentsBeFirst: "अभी तक कोई टिप्पणी नहीं है। पहले बनें!",
    minShort: "मिनट",
    hourShort: "घंटा",
    dayShort: "दिन",
    ago: "पहले",
    deleteQuestion: "प्रश्न हटाएं",
    confirmDeleteQuestion: "यह प्रश्न और इसके सभी उत्तर हटाएँ? यह पूर्ववत नहीं किया जा सकता।",
    failedToDelete: "हटाने में विफल।",
    failedToPostAnswer: "उत्तर पोस्ट करने में विफल।",
    questionFallbackTitle: "प्रश्न",
    someone: "कोई",
    discussionHeaderTitle: "चर्चा",
    vetDisclaimer: "कम्युनिटी की सलाह पशुचिकित्सक का विकल्प नहीं है। आपात स्थिति के लिए, अभी देखभाल खोजें।",
    noAnswersBeFirst: "अभी तक कोई उत्तर नहीं है — पहले बनें!",
    answersCountOne: "1 उत्तर",
    answersCountMany: "{count} उत्तर",
    member: "सदस्य",
    addAnswerPlaceholder: "एक उत्तर जोड़ें…",
    postBtnLabel: "पोस्ट",
    askedBy: "द्वारा पूछा गया",
    postsLabel: "पोस्ट",
    followersLabel: "फॉलोअर्स",
    followingLabel: "फॉलोइंग",
    editProfile: "प्रोफ़ाइल संपादित करें",
    messageLabel: "संदेश",
    blockUserTitle: "Block @{username}?",
    blockUserDesc: "वे आपकी प्रोफ़ाइल नहीं देख पाएंगे या आपसे संपर्क नहीं कर पाएंगे। उन्हें सूचित नहीं किया जाएगा कि आपने उन्हें ब्लॉक किया है।",
    blockAction: "ब्लॉक करें",
    unblockAction: "अनब्लॉक करें",
    failedToBlockUser: "उपयोगकर्ता को ब्लॉक करने में विफल",
    failedToUnblockUser: "उपयोगकर्ता को अनब्लॉक करने में विफल",
    couldNotIdentifyUserReport: "रिपोर्ट करने के लिए उपयोगकर्ता की पहचान नहीं की जा सकी।",
    accountNotAvailable: "यह खाता उपलब्ध नहीं है",
    blockedUserMessage: "आपने @{username} को ब्लॉक कर दिया है। उनकी प्रोफ़ाइल देखने के लिए अनब्लॉक करें।",
    cantViewProfile: "आप इस प्रोफ़ाइल को नहीं देख सकते।",
    accountIsPrivate: "यह खाता निजी है",
    followToSeePosts: "उनके पोस्ट देखने के लिए इस खाते को फॉलो करें।",
    // noPostsYet: "अभी तक कोई पोस्ट नहीं है।",
    noSavedPostsYet: "अभी तक कोई सहेजी गई पोस्ट नहीं है।",
    blockUserLabel: "@{username} को ब्लॉक करें",
    whyReportingUser: "आप इस उपयोगकर्ता की रिपोर्ट क्यों कर रहे हैं?",
    pets: "पालतू जानवर",
    saved: "सहेजे गए",
    notFollowingAnyoneYet: "अभी तक किसी को फॉलो नहीं कर रहे हैं",
    noFollowersYet: "अभी तक कोई फॉलोअर्स नहीं हैं",
    vetDetailsHeaderTitle: "पशु चिकित्सक विवरण",
    phoneUnavailableTitle: "फ़ोन अनुपलब्ध",
    phoneUnavailableMsg: "इस क्लिनिक के पास कोई फ़ोन नंबर सूचीबद्ध नहीं है।",
    callClinicTitle: "क्लिनिक पर कॉल करें",
    callClinicMsg: "{name} को {phone} पर कॉल करें।",
    couldNotOpenMaps: "मानचित्र नहीं खोला जा सका",
    clinicNotFound: "क्लिनिक नहीं मिला",
    vetClinicFallback: "पशु चिकित्सालय",
    ratingSuffix: "रेटिंग",
    openLabel: "खुला है",
    openInMaps: "मानचित्र में खोलें",
    hoursLabel: "कार्यकाल",
    setReminder: "अनुस्मारक सेट करें",
    locationLabel: "स्थान",
    contactLabel: "संपर्क",
    errorTitle: "त्रुटि",
    pleaseSelectPet: "कृपया एक पालतू जानवर चुनें",
    pleaseEnterReasonVisit: "कृपया यात्रा का कारण दर्ज करें",
    invalidVet: "अमान्य पशु चिकित्सक",
    successTitle: "सफलता",
    appointmentReminderSet: "अपॉइंटमेंट अनुस्मारक सेट किया गया!",
    errorBookingAppointment: "अपॉइंटमेंट बुक करने में त्रुटि",
    bookAppointmentHeaderTitle: "अपॉइंटमेंट बुक करें",
    reasonForVisitLabel: "यात्रा का कारण",
    reasonForVisitPlaceholder: "जैसे- वार्षिक टीकाकरण",
    confirmBooking: "बुकिंग की पुष्टि करें",
    bookingProgress: "बुकिंग हो रही है…",
    vetAppointmentReminderTitle: "पशु चिकित्सक अपॉइंटमेंट",
    reasonColonLabel: "कारण: {reason}",
    dateLabel: "दिनांक",
    timeLabel: "समय",
    sortDefault: "डिफ़ॉल्ट",
    sortAlphaAsc: "A → Z",
    sortAlphaDesc: "Z → A",
    sortRating: "शीर्ष रेटेड",
    sortDistance: "निकटतम पहले",
    sortLabel: "क्रमबद्ध करें",
    nearbyVetsHeaderTitle: "आस-पास के पशु चिकित्सक",
    searchClinicsPlaceholder: "क्लिनिक या शहर खोजें...",
    kmAway: "{distance} किमी दूर",
    locationNotSetTitle: "स्थान निर्धारित नहीं है",
    locationNotSetDesc: "आस-पास के पशु चिकित्सक देखने के लिए कृपया अपना गृह शहर सेट करें।",
    addLocationBtn: "स्थान जोड़ें",
    noVetsFound: "कोई पशु चिकित्सक नहीं मिला",
    noVetsFoundDesc: "दूसरा खोज या क्रमबद्ध प्रयास करें",
    generalCategory: "सामान्य",
    vetAppointmentTitleWithClinic: "पशु चिकित्सक अपॉइंटमेंट - {name}",
    pleaseEnterReminderTitle: "कृपया अनुस्मारक शीर्षक दर्ज करें",
    invalidDateTimeTitle: "अमान्य तिथि/समय",
    invalidDateTimeMsg: "आप उस तिथि और समय के लिए अनुस्मारक सेट नहीं कर सकते जो पहले ही बीत चुकी है। कृपया भविष्य का समय चुनें।",
    reminderUpdatedSuccess: "अनुस्मारक सफलतापूर्वक अपडेट किया गया!",
    reminderSetSuccess: "अनुस्मारक सफलतापूर्वक सेट किया गया!",
    errorSavingReminder: "अनुस्मारक सहेजने में त्रुटि",
    reminderTypeVaccination: "टीकाकरण",
    reminderTypeMedication: "दवा",
    reminderTypeGrooming: "सँवारना",
    reminderTypeOther: "अन्य",
    editReminderHeaderTitle: "अनुस्मारक संपादित करें",
    setReminderHeaderTitle: "अनुस्मारक सेट करें",
    reminderTitleLabel: "अनुस्मारक शीर्षक",
    reminderTitlePlaceholder: "जैसे- पशु चिकित्सक जांच अपॉइंटमेंट",
    reminderTypeLabel: "अनुस्मारक प्रकार",
    selectTypePlaceholder: "प्रकार चुनें",
    notesReasonLabel: "नोट्स / कारण",
    notesReasonPlaceholder: "विवरण, तैयारी निर्देश आदि जोड़ें।",
    savingChangesProgress: "परिवर्तन सहेजे जा रहे हैं…",
    saveChangesBtn: "परिवर्तन सुरक्षित करें",
    aboutAccountHeaderTitle: "इस खाते के बारे में",
    aboutAccountIntroText: "हमारे समुदाय को प्रामाणिक बनाए रखने में मदद के लिए, हम FurrCircle पर प्रोफ़ाइल के बारे में जानकारी दिखा रहे हैं।",
    dateJoinedLabel: "शामिल होने की तिथि",
    accountBasedInLabel: "खाता यहाँ आधारित है",
    july2015Fallback: "जुलाई 2015",
    indiaFallback: "भारत",
    categoryDogs: "कुत्ते",
    categoryCats: "बिल्लियां",
    categoryRescue: "बचाव",
    categoryHealth: "स्वास्थ्य",
    categoryTraining: "प्रशिक्षण",
    permissionRequiredTitle: "अनुमति आवश्यक है",
    galleryPermissionDesc: "कवर छवि अपलोड करने के लिए गैलरी पहुंच आवश्यक है।",
    requiredTitle: "आवश्यक",
    pleaseEnterCircleName: "कृपया सर्कल का नाम दर्ज करें।",
    errorCreatingCircleTitle: "सर्कल बनाने में त्रुटि",
    failedToCreateCircleMsg: "सर्कल बनाने में विफल।",
    createCircleHeaderTitle: "सर्कल बनाएं",
    coverImageLabel: "कवर छवि",
    changeCoverPhotoBtn: "कवर फ़ोटो बदलें",
    tapToAddCoverPhotoPlaceholder: "कवर फोटो जोड़ने के लिए टैप करें (वैकल्पिक)",
    nameLabel: "नाम",
    circleNamePlaceholder: "जैसे- बीगल बडीज़",
    descriptionLabel: "विवरण",
    circleDescPlaceholder: "यह सर्कल किस बारे में है?",
    categoryLabel: "श्रेणी",
    createCircleBtn: "सर्कल बनाएं",
    personalityFriendly: "मित्रवत",
    personalityPlayful: "चंचल",
    personalityCalm: "शांत",
    personalityActive: "सक्रिय",
    personalityIndependent: "स्वतंत्र",
    personalityCuddly: "प्यारा",
    personalityProtective: "रक्षक",
    personalityCurious: "जिज्ञासु",
    speciesDog: "कुत्ता",
    speciesCat: "बिल्ली",
    speciesRabbit: "खरगोश",
    speciesHorse: "घोड़ा",
    speciesPigeon: "कबूतर",
    speciesGoat: "बकरी",
    speciesCow: "गाय",
    speciesOther: "अन्य",
    permissionDeniedTitle: "अनुमति अस्वीकृत",
    allowLocationAccessSettings: "डिवाइस सेटिंग में स्थान पहुंच की अनुमति दें।",
    failedToFetchLocation: "स्थान प्राप्त करने में विफल।",
    pleaseEnterPetName: "कृपया अपने पालतू जानवर का नाम दर्ज करें।",
    pleaseSelectPetSpecies: "कृपया अपने पालतू जानवर की प्रजाति चुनें या दर्ज करें।",
    pleaseEnterPetBreed: "कृपया अपने पालतू जानवर की नस्ल दर्ज करें।",
    pleaseSelectPetDOB: "कृपया अपने पालतू जानवर की जन्म तिथि चुनें।",
    errorAddingPetTitle: "पालतू जानवर जोड़ने में त्रुटि",
    monthsShort: "{months} माह",
    lessThanOneMonth: "< 1 माह",
    addPetHeaderTitle: "पालतू जानवर जोड़ें",
    changePhotoBtn: "फ़ोटो बदलें",
    addPhotoBtn: "फ़ोटो जोड़ें",
    petNamePlaceholder: "जैसे- मूना",
    speciesLabel: "प्रजाति",
    selectSpeciesPlaceholder: "प्रजाति चुनें",
    customSpeciesLabel: "कस्टम प्रजाति",
    customSpeciesPlaceholder: "प्रजाति प्रकार दर्ज करें",
    breedLabel: "नस्ल",
    breedPlaceholder: "जैसे- बॉर्डर कोली",
    // weightLabel: "वजन",
    // weightPlaceholder: "जैसे- 12",
    genderLabel: "लिंग",
    femaleGenderOption: "♀ मादा",
    maleGenderOption: "♂ नर",
    dateOfBirthLabel: "जन्म तिथि",
    selectDateOfBirthPlaceholder: "जन्म तिथि चुनें",
    microchipIdLabel: "माइक्रोचिप आईडी",
    microchipIdPlaceholder: "जैसे- 981020000345119",
    personalityLabel: "व्यक्तित्व",
    savingProgress: "सहेज रहा है…",
    addPetBtn: "पालतू जानवर जोड़ें",
    pleaseWriteQuestionFirst: "कृपया पहले अपना प्रश्न लिखें।",
    failedToPostQuestionMsg: "प्रश्न पोस्ट करने में विफल।",
    askCommunityHeaderTitle: "समुदाय से पूछें",
    circleOptionalLabel: "सर्कल (वैकल्पिक)",
    globalCircleOption: "वैश्विक",
    questionLabel: "प्रश्न",
    questionPlaceholder: "आपका क्या प्रश्न है?",
    detailsOptionalLabel: "विवरण (वैकल्पिक)",
    shareMoreContextPlaceholder: "अधिक संदर्भ साझा करें…",
    tagsOptionalLabel: "टैग (वैकल्पिक, अल्पविराम से अलग)",
    tagsPlaceholder: "स्वास्थ्य, पोषण, प्रशिक्षण",
    postQuestionBtn: "प्रश्न पोस्ट करें",
    todayCelebration: "आज! 🎉",
    tomorrowCelebration: "कल!",
    inDaysCelebration: "{days} दिनों में",
    turningYearOld: "{age} साल का हो रहा है",
    turningYearsOld: "{age} साल का हो रहा है",
    petBirthdaysHeaderTitle: "पालतू जानवरों का जन्मदिन",
    upcomingCelebrationsTitle: "आगामी उत्सव",
    upcomingCelebrationsSub: "अपने प्यारे दोस्तों के विशेष दिनों को ट्रैक करें और तैयारी करें!",
    noBirthdaysFoundTitle: "कोई जन्मदिन नहीं मिला",
    noBirthdaysFoundSub: "सुनिश्चित करें कि आपने अपने पालतू जानवरों को जोड़ा है और उनकी जन्म तिथि निर्धारित की है! आप उनके जन्मदिन जोड़ने के लिए उनके पालतू प्रोफाइल को संपादित कर सकते हैं।",
    unblockUserTitle: "@{username} को अनब्लॉक करें?",
    unblockUserSub: "वे आपकी प्रोफ़ाइल देख सकेंगे और आपसे फिर से संपर्क कर सकेंगे।",
    unblockActionBtn: "अनब्लॉक करें",
    failedToUnblockMsg: "उपयोगकर्ता को अनब्लॉक करने में विफल।",
    blockedAccountsHeaderTitle: "ब्लॉक किए गए खाते",
    noBlockedAccountsTitle: "कोई ब्लॉक किया गया खाता नहीं",
    noBlockedAccountsSub: "आपके द्वारा ब्लॉक किए गए उपयोगकर्ता यहाँ दिखाई देंगे। आप उन्हें किसी भी समय अनब्लॉक कर सकते हैं।",
    blockedAccountsCountSingle: "{count} ब्लॉक किया गया खाता",
    blockedAccountsCountPlural: "{count} ब्लॉक किए गए खाते",
    unblockBtnLabel: "अनब्लॉक",
    monShort: "सोम",
    tueShort: "मंगल",
    wedShort: "बुध",
    thuShort: "गुरु",
    friShort: "शुक्र",
    satShort: "शनि",
    sunShort: "रवि",
    // bookAppointmentHeaderTitle: "अपॉइंटमेंट बुक करें",
    vetCardShortInfo: "सामान्य · सर्जरी · अभी खुला है",
    selectDateLabel: "तारीख चुनें",
    selectTimeLabel: "समय चुनें",
    confirmAppointmentBtn: "अपॉइंटमेंट की पुष्टि करें",
    bookAVetLabel: "पशु चिकित्सक बुक करें",
    logVaccineLabel: "टीका लॉग करें",
    logVitalsLabel: "महत्वपूर्ण संकेत लॉग करें",
    logMedsLabel: "दवाएं लॉग करें",
    careAndHealthHeaderTitle: "देखभाल और स्वास्थ्य",
    reminderLabel: "अनुस्मारक",
    monthlyCheckupDueMsg: "इस सप्ताह मासिक जांच होनी है",
    bookNowBtn: "अभी बुक करें",
    careServicesLabel: "देखभाल सेवाएँ",
    medicalRecordsTile: "चिकित्सा रिकॉर्ड",
    petPassportTile: "पालतू पासपोर्ट",
    whosePassportQuestion: "किसका पासपोर्ट?",
    whichPetQuestion: "कौन सा पालतू जानवर?",
    selectPetPassportSub: "उनका पासपोर्ट देखने के लिए एक पालतू जानवर चुनें",
    selectPetRecordsSub: "स्वास्थ्य रिकॉर्ड देखने के लिए एक पालतू जानवर चुनें",
    yearsShort: "{years} साल",
  },
  te: {
    profile: "ప్రొఫైల్",
    myPets: "నా పెంపుడు జంతువులు",
    upcomingReminders: "రాబోయే రిమైండర్‌లు",
    logCare: "సంరక్షణను నమోదు చేయండి",
    quickAccess: "త్వరిత ప్రాప్యత",
    activity: "కార్యాచరణ",
    signOut: "సాఇన్ అవుట్",
    language: "భాష",
    selectLanguage: "భాషను ఎంచుకోండి",
    english: "ఇంగ్లీష్ (English)",
    hindi: "హిందీ (Hindi)",
    telugu: "తెలుగు (Telugu)",
    settings: "సెట్టింగులు",
    chooseLanguage: "భాషను ఎంచుకోండి",
    cancel: "రద్దు చేయి",
    addPet: "పెంపుడు జంతువును జోడించు",
    medicalRecords: "వైద్య రికార్డులు",
    petPassport: "పెట్ పాస్‌పోర్ట్",
    today: "ఈరోజు",
    events: "ఈవెంట్స్",
    lostFound: "కోల్పోయినవి & దొరికినవి",
    care: "సంరక్షణ",
    notifications: "నోటిఫికేషన్లు",
    messages: "సందేశాలు",
    badgesAchievements: "బ్యాడ్జీలు & విజయాలు",
    nothingInFeedYet: "మీ ఫీడ్‌లో ఇంకా ఏమీ లేదు",
    allCaughtUp: "మీరు పూర్తిగా అప్‌డేట్ అయ్యారు",
    followToFillFeed: "మీ ఫీడ్‌ను నింపడానికి వ్యక్తులను అనుసరించండి లేదా పోస్ట్ చేయండి. ఇతరులు ఏమి భాగస్వామ్యం చేస్తున్నారో చూడాలనుకుంటున్నారా?",
    seenAllPosts: "మీరు అనుసరించే వ్యక్తుల నుండి అన్ని పోస్ట్‌లను చూసేశారు. మరిన్ని విషయాలను అన్వేషించాలనుకుంటున్నారా?",
    showSuggestedPosts: "సూచించబడిన పోస్ట్‌లను చూపించు",
    suggestedForYou: "మీ కొరకు సూచించబడినవి",
    yourStory: "మీ కథ",
    addStory: "కథను జోడించు",
    chooseStorySource: "మీ కథ కోసం media మూలాన్ని ఎంచుకోండి",
    openCamera: "కెమెరాను తెరువు",
    chooseFromGallery: "గ్యాలరీ నుండి ఎంచుకోండి",
    permissionRequired: "అనుమతి అవసరం",
    allowGalleryAccess: "కథలను భాగస్వామ్యం చేయడానికి దయచేసి గ్యాలరీ యాక్సెస్‌ను అనుమతించండి.",
    allowCameraAccess: "కథలను చిత్రీకరించడానికి దయచేసి కెమెరా యాక్సెస్‌ను అనుమతించండి.",
    videoTooLong: "వీడియో చాలా పొడవుగా ఉంది",
    selectShorterVideo: "దయచేసి 30 సెకన్ల కంటే తక్కువ వ్యవధి గల వీడియోను ఎంచుకోండి.",
    noPostsYet: "ఇంకా పోస్ట్‌లు లేవు",
    shareFirstMoment: "మీ పెంపుడు జంతువు యొక్క మొదటి క్షణాన్ని పంచుకునే మొదటి వ్యక్తి అవ్వండి!",
    selectLocation: "స్థానాన్ని ఎంచుకోండి",
    error: "లోపం",
    failedToSaveLocation: "స్థానాన్ని సేవ్ చేయడం విఫలమైంది.",
    compressing: "కంప్రెస్ అవుతోంది...",
    deletePost: "పోస్ట్‌ను తొలగించు",
    confirmDeletePost: "మీరు ఖచ్చితంగా ఈ పోస్ట్‌ను తొలగించాలనుకుంటున్నారా?",
    delete: "తొలగించు",
    success: "విజయం",
    postDeletedSuccessfully: "పోస్ట్ విజయవంతంగా తొలగించబడింది.",
    couldNotDeletePost: "పోస్ట్‌ను తొలగించడం साధ్యం కాలేదు.",
    couldNotIdentifyUser: "రిపోర్ట్ చేయడానికి వినియోగదారుని గుర్తించలేకపోయాము.",
    failedToSubmitReport: "రిపోర్ట్‌ను సమర్పించడం విఫలమైంది.",
    petParent: "పెంపుడు జంతువు యజమాని",
    couldNotPostComment: "వ్యాఖ్యను పోస్ట్ చేయడం సాధ్యం కాలేదు.",
    comments: "వ్యాఖ్యలు",
    noCommentsYet: "ఇంకా వ్యాఖ్యలు లేవు. సంభాషణను ప్రారంభించండి!",
    addCommentPlaceholder: "వ్యాఖ్యను జోడించు...",
    post: "పోస్ట్",
    options: "ఎంపికలు",
    removeFromSaved: "సేవ్ చేసిన వాటి నుండి తీసివేయి",
    savePost: "పోస్ట్‌ను సేవ్ చేయి",
    editPost: "పోస్ట్‌ను సవరించు",
    aboutThisAccount: "ఈ ఖాతా గురించి",
    report: "రిపోర్ట్ చేయి",
    whyReportingPost: "మీరు ఈ పోస్ట్‌ను ఎందుకు రిపోర్ట్ చేస్తున్నారు?",
    reportDisclaimer: "మీ రిపోర్ట్ అనామకంగా ఉంటుంది. ఎవరైనా తక్షణ ప్రమాదంలో ఉంటే, స్థానిక అత్యవసర సేవలకు కాల్ చేయండి - వేచి ఉండకండి.",
    thanksFeedback: "మీ అభిప్రాయానికి ధన్యవాదాలు",
    reportFeedbackDetail: "భవిష్యత్తులో మీకు ఇలాంటి కంటెంట్‌ను తక్కువగా చూపించడానికి మేము ఈ రిపోర్ట్‌లను ఉపయోగిస్తాము.",
    done: "పూర్తయింది",
    noPetsFound: "పెంపుడు జంతువులు ఏవీ కనుగొనబడలేదు",
    addPetToProfileBeforeMemory: "దయచేసి మెమరీని జోడించే ముందు మీ ప్రొఫైల్‌కు పెంపుడు జంతువును జోడించండి.",
    failedRetrievePets: "మీ పెంపుడు జంతువులను పొందడం విఫలమైంది.",
    create: "సృష్టించు",
    newPost: "కొత్త పోస్ట్",
    sharePetPhoto: "మీ పెంపుడు జంతువు ఫోటోను భాగస్వామ్యం చేయండి",
    askCommunity: "కమ్యూనిటీని అడగండి",
    getPetHelp: "పెంపుడు జంతువుల యజమానుల నుండి సహాయం పొందండి",
    addMemory: "మెమరీని జోడించు",
    saveToVault: "వాల్ట్‌కు సేవ్ చేయి",
    selectPet: "పెంపుడు జంతువును ఎంచుకోండి",
    reasonDontLikeIt: "నాకు ఇది నచ్చలేదు",
    reasonBullying: "వేధించడం లేదా అవాంఛిత సంప్రదింపులు",
    reasonSuicideSelfInjury: "ఆత్మహత్య, స్వయం గాయాలు లేదా ఆహార లోపాలు",
    reasonViolenceHate: "హింస, ద్వేషం లేదా దోపిడీ",
    reasonRestrictedItems: "పరిమితం చేయబడిన వస్తువులను అమ్మడం లేదా ప్రోత్సహించడం",
    reasonNudity: "నగ్నత్వం లేదా లైంగిక కార్యకలాపాలు",
    reasonScamSpam: "స్కామ్, మోసం లేదా స్పామ్",
    reasonFalseInfo: "తప్పుడు సమాచారం",
    reasonIntellectualProperty: "మేధో సంపత్తి",
    justNow: "ఇప్పుడే",
    minuteAgo: "1 నిమిషం క్రితం",
    minutesAgo: "నిమిషాల క్రితం",
    hourAgo: "1 గంట క్రితం",
    hoursAgo: "గంటల క్రితం",
    dayAgo: "1 రోజు క్రితం",
    daysAgo: "రోజుల క్రితం",
    weekAgo: "1 వారం క్రితం",
    weeksAgo: "వారాల క్రితం",
    monthAgo: "1 నెల క్రితం",
    monthsAgo: "నెలల క్రితం",
    yearAgo: "1 సంవత్సరం క్రితం",
    yearsAgo: "సంవత్సరాల క్రితం",
    communityTitle: "సర్కిల్స్",
    communitySubtitle: "పెంపుడు జంతువుల యజమానులను ఒకచోట చేర్చే సంభాషణలు",
    searchPlaceholder: "ప్రజలు, పెంపుడు జంతువులు, సర్కిల్స్, పోస్ట్‌లను శోధించండి...",
    typeToSearch: "సర్కిల్స్, పోస్ట్‌లు మరియు ప్రశ్నలను శోధించడానికి టైప్ చేయండి",
    noResultsFor: "ఫలితాలు లేవు",
    tryDifferentKeyword: "మరొక పేరు లేదా కీవర్డ్‌ని ప్రయత్నించండి",
    follow: "అనుసరించండి",
    requested: "అభ్యర్థించబడింది",
    following: "అనుసరిస్తున్నారు",
    joined: "చేరారు",
    join: "చేరండి",
    upvotes: "అప్‌వోట్లు",
    upvoted: "అప్‌వోట్ చేయబడింది ✓",
    answers: "సమాధానాలు",
    replies: "సమాధానాలు",
    trendingToday: "ఈరోజు ట్రెండింగ్",
    noTrendingQuestions: "ఇంకా ట్రెండింగ్ ప్రశ్నలు లేవు. మొదటిగా మీరే అడగండి!",
    yourCircles: "మీ సర్కిల్స్",
    discoverCircles: "సర్కిల్స్‌ను అన్వేషించండి",
    notJoinedCircles: "మీరు ఇంకా ఏ సర్కిల్స్‌లో చేరలేదు. క్రింద కొన్ని అన్వేషించండి!",
    members: "సభ్యులు",
    actionFailed: "చర్య విఫలమైంది.",
    filterAll: "అన్నీ",
    filterPeople: "ప్రజలు",
    filterPets: "పెంపుడు జంతువులు",
    filterPosts: "పోస్ట్‌లు",
    filterCircles: "సర్కిల్స్",
    filterQuestions: "ప్రశ్నలు",
    filterTags: "#ట్యాగ్‌లు",
    seeAll: "అన్నీ చూడండి",
    lookingForForeverHome: "శాశ్వత ఇల్లు కోసం చూస్తున్నారు",
    noPetsYet: "ఇంకా పెంపుడు జంతువులు లేవు",
    has: "కలిగి ఉన్నారు",
    messageOwner: "యజమానికి సందేశం పంపండి 💬",
    pending: "పెండింగ్ ⏳",
    declined: "తిరస్కరించబడింది ❌",
    imInterested: "నాకు ఆసక్తి ఉంది 🐾",
    somethingWentWrong: "ఏదో తప్పు జరిగింది",
    couldNotLoadCards: "కార్డులను లోడ్ చేయలేకపోయాము. మీ కనెక్షన్‌ని తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.",
    tryAgain: "మళ్లీ ప్రయత్నించండి",
    enableBreedMode: "బ్రీడ్ మోడ్‌ను ప్రారంభించండి",
    enableBreedModeDesc: "జతలను కనుగొనడానికి మీ పెంపుడు జంతువు ప్రొఫైల్‌కు వెళ్లి బ్రీడింగ్ మోడ్‌ను ఆన్ చేయండి.",
    addPetFirst: "ముందుగా ఒక పెంపుడు జంతువును జోడించండి",
    addPetFirstDesc: "సమీపంలో ఆడుకునే భాగస్వాములను కనుగొనడం ప్రారంభించడానికి మీ పెంపుడు జంతువును జోడించండి.",
    noMoreCards: "ప్రస్తుతానికి ఇంకా కార్డులు లేవు. తర్వాత మళ్లీ చూడండి.",
    refresh: "రిఫ్రెష్ చేయండి",
    playdateTitle: "ప్లేడేట్",
    likeStamp: "లైక్",
    nopeStamp: "నో",
    itsAMatch: "మ్యాచ్ కుదిరింది!",
    youAnd: "మీరు మరియు",
    bothSaidYes: "ఇద్దరూ అవును అన్నారు!",
    startChatting: "చాటింగ్ ప్రారంభించండి",
    keepSwiping: "స్వైప్ చేస్తూ ఉండండి",
    discoverTitle: "అన్వేషించండి",
    discoverSubtitle: "మీకు సమీపంలోని పశువైద్యులు, పెంపుడు జంతువులు & ప్రదేశాలు",
    nearbyVets: "సమీపంలోని పశువైద్యులు",
    addLocation: "స్థానాన్ని జోడించండి",
    setLocationDesc: "సమీపంలోని పశువైద్యులను కనుగొనడానికి మీ నగరాన్ని సెట్ చేయండి",
    findingVetsNear: "సమీపంలో పశువైద్యులను కనుగొంటున్నారు",
    noVetsFoundNear: "సమీపంలో పశువైద్యులు ఎవరూ కనుగొనబడలేదు",
    petsNearby: "సమీపంలోని పెంపుడు జంతువులు",
    petsFound: "కనుగొనబడ్డాయి",
    modeAll: "అన్నీ",
    modeAdoption: "దత్తత",
    modeFoster: "పోషణ",
    adoptBadge: "దత్తత",
    fosterBadge: "పోషణ",
    nearby: "సమీపంలో",
    noPetsMatchFilter: "మీకు సమీపంలో ఈ ఫిల్టర్‌కు సరిపోయే పెంపుడు జంతువులు ఏవీ ఇంకా లేవు.",
    leaveCircleAlertTitle: "సర్కిల్ నుండి నిష్క్రమించండి",
    leaveCircleAlertMsg: "మీరు ఖచ్చితంగా నిష్క్రమించాలనుకుంటున్నారా",
    leave: "నిష్క్రమించండి",
    failedToLeaveCircle: "సర్కిల్ నుండి నిష్క్రమించడం విఫలమైంది.",
    deleteCircleAlertTitle: "సర్కిల్‌ను తొలగించండి",
    deleteCircleAlertMsg: "శాశ్వతంగా తొలగించండి",
    deleteCircleAlertMsg2: "ఇది దాని అన్ని చర్చలను తొలగిస్తుంది మరియు దీనిని తిరిగి చేయలేము.",
    failedToDeleteCircle: "సర్కిల్‌ను తొలగించడం విఫలమైంది.",
    joinInviteMsg: "చేరండి",
    joinInviteMsg2: "on FurrCircle!",
    circleHeaderTitle: "సర్కిల్",
    circleNotFound: "సర్కిల్ కనుగొనబడలేదు",
    inviteMembers: "సభ్యులను ఆహ్వానించండి",
    joinCircle: "సర్కిల్‌లో చేరండి",
    discussions: "చర్చలు",
    ask: "అడగండి",
    noDiscussionsYet: "ఇంకా చర్చలు లేవు. మొదటిగా మీరే అడగండి!",
    byAuthor: "ద్వారా",
    sendToFriend: "స్నేహితుడికి పంపండి",
    editCircle: "సర్కిల్‌ను సవరించండి",
    deleteCircle: "సర్కిల్‌ను తొలగించండి",
    leaveCircle: "సర్కిల్ నుండి నిష్క్రమించండి",
    couldNotLoadEventDetails: "ఈవెంట్ వివరాలను లోడ్ చేయడం సాధ్యం కాలేదు.",
    bookingSuccessTitle: "మీరు నమోదు చేసుకున్నారు! 🎉",
    bookingSuccessMsg: "ఈ ఈవెంట్ కోసం మీ స్థానం కేటాయించబడింది.",
    bookingFailedTitle: "బుకింగ్ విఫలమైంది",
    eventDetailsHeaderTitle: "ఈవెంట్ వివరాలు",
    eventNotFound: "ఈవెంట్ కనుగొనబడలేదు",
    goingBadge: "✓ వెళ్తున్నారు",
    eventDateLabel: "తేదీ",
    eventTimeLabel: "సమయం",
    eventLocationLabel: "స్థానం",
    eventAttendingLabel: "హాజరవుతున్నారు",
    tba: "త్వరలో తెలియజేయబడుతుంది",
    peopleGoing: "మంది వెళ్తున్నారు",
    aboutEvent: "గురించి",
    goingBtn: "మీరు వెళ్తున్నారు! 🎉",
    bookRsvpBtn: "బుక్ చేయండి / RSVP",
    pleaseEnterMedicationName: "దయచేసి ఔషధం పేరును నమోదు చేయండి.",
    noPetSelected: "పెంపుడు జంతువు ఎంపిక చేయబడలేదు.",
    medicationUpdatedSuccessfully: "ఔషధం విజయవంతంగా నవీకరించబడింది.",
    medicationLoggedSuccessfully: "ఔషధం విజయవంతంగా నమోదు చేయబడింది.",
    failedToSaveMedication: "ఔషధాన్ని సేవ్ చేయడం విఫలమైంది.",
    editMedicationHeaderTitle: "ఔషధాన్ని సవరించండి",
    logMedicationHeaderTitle: "ఔషధాన్ని నమోదు చేయండి",
    medicationNameLabel: "ఔషధం పేరు",
    medicationNamePlaceholder: "ఉదా. నెక్స్‌గార్డ్",
    medicationDoseLabel: "మోతాదు",
    medicationDosePlaceholder: "ఉదా. 1 టాబ్లెట్",
    medicationNotesLabel: "గమనికలు",
    medicationNotesPlaceholder: "ఏవైనా పరిశీలనలు...",
    medicationPhotoLabel: "ఔషధ ఫోటో",
    changePhoto: "ఫోటో మార్చండి",
    addPhoto: "ఫోటోను జోడించండి",
    save: "సేవ్ చేయి",
    pleaseEnterVaccineName: "దయచేసి వ్యాక్సిన్ పేరును నమోదు చేయండి.",
    vaccineUpdatedSuccessfully: "వ్యాక్సిన్ విజయవంతంగా నవీకరించబడింది.",
    vaccineLoggedSuccessfully: "వ్యాక్సిన్ విజయవంతంగా నమోదు చేయబడింది.",
    failedToSaveVaccine: "వ్యాక్సిన్‌ను సేవ్ చేయడం విఫలమైంది.",
    editVaccineHeaderTitle: "వ్యాక్సిన్‌ను సవరించండి",
    logVaccineHeaderTitle: "వ్యాక్సిన్‌ను నమోదు చేయండి",
    vaccineNameLabel: "వ్యాక్సిన్ పేరు",
    vaccineNamePlaceholder: "ఉదా. DHPP",
    vaccineDateGivenLabel: "ఇచ్చిన తేదీ",
    vaccineNextDueDateLabel: "తదుపరి గడువు తేదీ",
    clear: "క్లియర్ చేయి",
    selectDateOptional: "తేదీని ఎంచుకోండి (ఐచ్ఛికం)",
    setReminderNextDueDate: "తదుపరి గడువు తేదీకి రిమైండర్‌ని సెట్ చేయండి",
    pleaseEnterAtLeastOneVital: "దయచేసి కనీసం బరువు, ఉష్ణోగ్రత లేదా హృదయ స్పందన రేటును నమోదు చేయండి.",
    pleaseWait: "దయచేసి వేచి ఉండండి",
    stillLoadingPetInfo: "ఇంకా పెంపుడు జంతువు సమాచారాన్ని లోడ్ చేస్తోంది...",
    invalidTemperatureTitle: "అమాన్యమైన ఉష్ణోగ్రత",
    invalidTempMsg: "{species} కోసం, ఉష్ణోగ్రత తప్పనిసరిగా {min}°C మరియు {max}°C మధ్య ఉండాలి.",
    invalidHeartRateTitle: "అమాన్యమైన హృదయ స్పందన రేటు",
    invalidHrMsg: "{species} కోసం, హృదయ స్పందన రేటు తప్పనిసరిగా {min} మరియు {max} bpm మధ్య ఉండాలి.",
    vitalsUpdatedSuccessfully: "వైటల్స్ విజయవంతంగా నవీకరించబడ్డాయి.",
    vitalsLoggedSuccessfully: "వైటల్స్ విజయవంతంగా నమోదు చేయబడ్డాయి.",
    failedToSaveVitals: "వైటల్స్ సేవ్ చేయడం విఫలమైంది.",
    editVitalsHeaderTitle: "వైటల్స్‌ను సవరించండి",
    logVitalsHeaderTitle: "వైటల్స్‌ను నమోదు చేయండి",
    weightLabel: "బరువు (కిలోలు)",
    weightPlaceholder: "ఉదా. 14.2",
    temperatureLabel: "ఉష్ణోగ్రత (°C)",
    temperaturePlaceholder: "ఉదా. 38.5",
    normalRange: "సాధారణ పరిధి:",
    heartRateLabel: "హృదయ స్పందన రేటు (bpm)",
    heartRatePlaceholder: "ఉదా. 80",
    vitalsNotesLabel: "గమనికలు",
    vitalsNotesPlaceholder: "ఏవైనా పరిశీలనలు...",
    fosterAction: "పోషణ",
    adoptAction: "దత్తత",
    petInterestMessage: "నేను మీ {name} అనే పెంపుడు జంతువును {action} చేయడానికి ఆసక్తి కలిగి ఉన్నాను! furrcircle://pet/{id}",
    failedStartConversationOwner: "యజమానితో సంభాషణను ప్రారంభించడం విఫలమైంది.",
    petProfileHeaderTitle: "పెంపుడు జంతువు ప్రొఫైల్",
    petNotFound: "పెంపుడు జంతువు కనుగొనబడలేదు.",
    unknownBreed: "తెలియని జాతి",
    years: "సంవత్సరాలు",
    noBioAvailable: "బయో అందుబాటులో లేదు.",
    unknownLocation: "తెలియదు",
    verified: "ధృవీకరించబడింది",
    ageLabel: "వయస్సు",
    weightStatLabel: "బరువు",
    cityLabel: "నగరం",
    personalitySectionTitle: "వ్యక్తిత్వం",
    noTraitsSpecified: "లక్షణాలు ఏవీ పేర్కొనబడలేదు.",
    gallerySectionTitle: "గ్యాలరీ",
    noMemory: "మెమరీ లేదు",
    noPhoto: "ఫోటో లేదు",
    messageOwnerBtn: "యజమానికి సందేశం పంపండి",
    ok: "సరే",
    parent: "యజమాని",
    failedToLoadPost: "పోస్ట్‌ను లోడ్ చేయడం విఫలమైంది.",
    postHeaderTitle: "పోస్ట్",
    postNotFound: "పోస్ట్ కనుగొనబడలేదు.",
    noCommentsBeFirst: "ఇంకా వ్యాఖ్యలు లేవు. మొదటిగా రాయండి!",
    minShort: "నిమి",
    hourShort: "గం",
    dayShort: "రో",
    ago: "క్రితం",
    deleteQuestion: "ప్రశ్నను తొలగించు",
    confirmDeleteQuestion: "ఈ ప్రశ్నను మరియు దాని అన్ని సమాధానాలను తొలగించాలా? దీన్ని తిరిగి పొందలేము.",
    failedToDelete: "తొలగించడం విఫలమైంది.",
    failedToPostAnswer: "సమాధానం పోస్ట్ చేయడం విఫలమైంది.",
    questionFallbackTitle: "ప్రశ్న",
    someone: "ఎవరో",
    discussionHeaderTitle: "చర్చ",
    vetDisclaimer: "కమ్యూనిటీ సలహా పశువైద్యునికి ప్రత్యామ్నాయం కాదు. అత్యవసర పరిస్థితుల కోసం, ఇప్పుడే సంరక్షణను కనుగొనండి.",
    noAnswersBeFirst: "ఇంకా సమాధానాలు లేవు — మొదటిగా ఉండండి!",
    answersCountOne: "1 సమాధానం",
    answersCountMany: "{count} సమాధానాలు",
    member: "సభ్యుడు",
    addAnswerPlaceholder: "ఒక సమాధానాన్ని జోడించండి...",
    postBtnLabel: "పోస్ట్",
    askedBy: "అడిగిన వారు",
    postsLabel: "పోస్ట్‌లు",
    followersLabel: "ఫాలోవర్స్",
    followingLabel: "ఫాలోయింగ్",
    editProfile: "ప్రొఫైల్ ఎడిట్ చేయి",
    messageLabel: "సందేశం",
    blockUserTitle: "Block @{username}?",
    blockUserDesc: "వారు మీ ప్రొఫైల్‌ను చూడలేరు లేదా మిమ్మల్ని సంప్రదించలేరు. మీరు వారిని బ్లాక్ చేసినట్లు వారికి తెలియజేయబడదు.",
    blockAction: "బ్లాక్ చేయి",
    unblockAction: "అన్‌బ్లాక్ చేయి",
    failedToBlockUser: "వినియోగదారుని బ్లాక్ చేయడం విఫలమైంది",
    failedToUnblockUser: "వినియోగదారుని అన్‌బ్లాక్ చేయడం విఫలమైంది",
    couldNotIdentifyUserReport: "నివేదించడానికి వినియోగదారుని గుర్తించలేకపోయాము.",
    accountNotAvailable: "ఈ ఖాతా అందుబాటులో లేదు",
    blockedUserMessage: "మీరు @{username} ని బ్లాక్ చేసారు. వారి ప్రొఫైల్‌ని చూడటానికి అన్‌బ్లాక్ చేయండి.",
    cantViewProfile: "మీరు ఈ ప్రొఫైల్‌ను చూడలేరు.",
    accountIsPrivate: "ఈ ఖాతా ప్రైవేట్",
    followToSeePosts: "వారి పోస్ట్‌లను చూడటానికి ఈ ఖాతాను ఫాలో అవ్వండి.",
    // noPostsYet: "ఇంకా పోస్ట్‌లు లేవు.",
    noSavedPostsYet: "ఇంకా సేవ్ చేసిన పోస్ట్‌లు లేవు.",
    blockUserLabel: "@{username} ని బ్లాక్ చేయి",
    whyReportingUser: "మీరు ఈ వినియోగదారుని ఎందుకు నివేదిస్తున్నారు?",
    pets: "పెంపుడు జంతువులు",
    saved: "సేవ్ చేయబడినవి",
    notFollowingAnyoneYet: "ఇంకా ఎవరినీ ఫాలో అవ్వడం లేదు",
    noFollowersYet: "ఇంకా ఫాలోవర్స్ లేరు",
    vetDetailsHeaderTitle: "పశువైద్యుని వివరాలు",
    phoneUnavailableTitle: "ఫోన్ అందుబాటులో లేదు",
    phoneUnavailableMsg: "ఈ క్లినిక్‌కి ఎలాంటి ఫోన్ నంబర్ లిస్ట్ చేయబడలేదు.",
    callClinicTitle: "క్లినిక్‌కి కాల్ చేయండి",
    callClinicMsg: "{name} కి {phone} లో కాల్ చేయండి.",
    couldNotOpenMaps: "మ్యాప్‌లను తెరవలేకపోయాము",
    clinicNotFound: "క్లినిక్ కనుగొనబడలేదు",
    vetClinicFallback: "పశువైద్య క్లినిక్",
    ratingSuffix: "రేటింగ్",
    openLabel: "తెరిచి ఉంది",
    openInMaps: "మ్యాప్‌లో తెరవండి",
    hoursLabel: "పని గంటలు",
    setReminder: "రిమైండర్ సెట్ చేయి",
    locationLabel: "స్థానం",
    contactLabel: "సంప్రదించండి",
    errorTitle: "తప్పు",
    pleaseSelectPet: "దయచేసి ఒక పెంపుడు జంతువును ఎంచుకోండి",
    pleaseEnterReasonVisit: "దయచేసి సందర్శించడానికి గల కారణాన్ని నమోదు చేయండి",
    invalidVet: "చెల్లని పశువైద్యుడు",
    successTitle: "విజయం",
    appointmentReminderSet: "అపాయింట్‌మెంట్ రిమైండర్ సెట్ చేయబడింది!",
    errorBookingAppointment: "అపాయింట్‌మెంట్ బుక్ చేయడంలో లోపం",
    bookAppointmentHeaderTitle: "అపాయింట్‌మెంట్ బుక్ చేయి",
    reasonForVisitLabel: "సందర్శన కారణం",
    reasonForVisitPlaceholder: "ఉదా. వార్షిక టీకా",
    confirmBooking: "బుకింగ్‌ని ధృవీకరించు",
    bookingProgress: "బుకింగ్ అవుతోంది...",
    vetAppointmentReminderTitle: "పశువైద్యుని అపాయింట్‌మెంట్",
    reasonColonLabel: "కారణం: {reason}",
    dateLabel: "తేదీ",
    timeLabel: "సమయం",
    sortDefault: "డిఫాల్ట్",
    sortAlphaAsc: "A → Z",
    sortAlphaDesc: "Z → A",
    sortRating: "టాప్ రేటింగ్",
    sortDistance: "సమీపంలో ఉన్నవి మొదట",
    sortLabel: "క్రమబద్ధీకరించు",
    nearbyVetsHeaderTitle: "సమీప పశువైద్యులు",
    searchClinicsPlaceholder: "క్లినిక్‌లు లేదా నగరాన్ని శోధించండి...",
    kmAway: "{distance} కిమీ దూరంలో",
    locationNotSetTitle: "స్థానం సెట్ చేయబడలేదు",
    locationNotSetDesc: "సమీపంలోని పశువైద్యులను చూడటానికి దయచేసి మీ నివాస నగరాన్ని సెట్ చేయండి.",
    addLocationBtn: "స్థానాన్ని జోడించండి",
    noVetsFound: "పశువైద్యులు కనుగొనబడలేదు",
    noVetsFoundDesc: "మరొక శోధన లేదా క్రమబద్ధీకరణను ప్రయత్నించండి",
    generalCategory: "సాధారణ",
    vetAppointmentTitleWithClinic: "పశువైద్యుని అపాయింట్‌మెంట్ - {name}",
    pleaseEnterReminderTitle: "దయచేసి రిమైండర్ శీర్షికను నమోదు చేయండి",
    invalidDateTimeTitle: "చెల్లని తేదీ/సమయం",
    invalidDateTimeMsg: "గతించిన తేదీ మరియు సమయానికి మీరు రిమైండర్‌ను సెట్ చేయలేరు. దయచేసి భవిష్యత్ సమయాన్ని ఎంచుకోండి.",
    reminderUpdatedSuccess: "రిమైండర్ విజయవంతంగా నవీకరించబడింది!",
    reminderSetSuccess: "రిమైండర్ విజయవంతంగా సెట్ చేయబడింది!",
    errorSavingReminder: "రిమైండర్‌ను సేవ్ చేయడంలో లోపం",
    reminderTypeVaccination: "టీకా",
    reminderTypeMedication: "మందులు",
    reminderTypeGrooming: "గ్రూమింగ్",
    reminderTypeOther: "ఇతర",
    editReminderHeaderTitle: "రిమైండర్‌ను సవరించు",
    setReminderHeaderTitle: "రిమైండర్ సెట్ చేయి",
    reminderTitleLabel: "రిమైండర్ శీర్షిక",
    reminderTitlePlaceholder: "ఉదా. పశువైద్యుని తనిఖీ అపాయింట్‌మెంట్",
    reminderTypeLabel: "రిమైండర్ రకం",
    selectTypePlaceholder: "రకాన్ని ఎంచుకోండి",
    notesReasonLabel: "గమనికలు / కారణం",
    notesReasonPlaceholder: "వివరాలు, ప్రిపరేషన్ సూచనలు మొదలైనవి జోడించండి.",
    savingChangesProgress: "మార్పులను సేవ్ చేస్తోంది...",
    saveChangesBtn: "మార్పులను సేవ్ చేయి",
    aboutAccountHeaderTitle: "ఈ ఖాతా గురించి",
    aboutAccountIntroText: "మా కమ్యూనిటీని ప్రామాణికంగా ఉంచడంలో సహాయపడటానికి, మేము FurrCircle లో ప్రొఫైల్‌ల గురించిన సమాచారాన్ని చూపిస్తున్నాము.",
    dateJoinedLabel: "చేరిన తేదీ",
    accountBasedInLabel: "ఖాతా ఆధారిత ప్రాంతం",
    july2015Fallback: "జూలై 2015",
    indiaFallback: "భారతదేశం",
    categoryDogs: "కుక్కలు",
    categoryCats: "పిల్లులు",
    categoryRescue: "రెస్క్యూ",
    categoryHealth: "ఆరోగ్యం",
    categoryTraining: "శిక్షణ",
    permissionRequiredTitle: "అనుమతి అవసరం",
    galleryPermissionDesc: "కవర్ చిత్రాన్ని అప్‌లోడ్ చేయడానికి గ్యాలరీ యాక్సెస్ అవసరం.",
    requiredTitle: "అవసరం",
    pleaseEnterCircleName: "దయచేసి సర్కిల్ పేరును నమోదు చేయండి.",
    errorCreatingCircleTitle: "సర్కిల్‌ను సృష్టించడంలో లోపం",
    failedToCreateCircleMsg: "సర్కిల్‌ను సృష్టించడంలో విఫలమైంది.",
    createCircleHeaderTitle: "సర్కిల్‌ను సృష్టించు",
    coverImageLabel: "కవర్ చిత్రం",
    changeCoverPhotoBtn: "కవర్ ఫోటోను మార్చండి",
    tapToAddCoverPhotoPlaceholder: "కవర్ ఫోటోను జోడించడానికి నొక్కండి (ఐచ్ఛికం)",
    nameLabel: "పేరు",
    circleNamePlaceholder: "ఉదా. బీగల్ బడ్డీస్",
    descriptionLabel: "వివరణ",
    circleDescPlaceholder: "ఈ సర్కిల్ దేని గురించి?",
    categoryLabel: "వర్గం",
    createCircleBtn: "సర్కిల్‌ను సృష్టించు",
    personalityFriendly: "స్నేహపూర్వక",
    personalityPlayful: "ఆటపాటల",
    personalityCalm: "ప్రశాంతంగా",
    personalityActive: "చురుకైన",
    personalityIndependent: "స్వతంత్ర",
    personalityCuddly: "ముద్దులొలికే",
    personalityProtective: "రక్షణ",
    personalityCurious: "కుతూహలం",
    speciesDog: "కుక్క",
    speciesCat: "పిల్లి",
    speciesRabbit: "కుందేలు",
    speciesHorse: "గుర్రం",
    speciesPigeon: "పావురం",
    speciesGoat: "మేక",
    speciesCow: "ఆవు",
    speciesOther: "ఇతర",
    permissionDeniedTitle: "అనుమతి నిరాకరించబడింది",
    allowLocationAccessSettings: "పరికరం సెట్టింగ్‌లలో స్థాన యాక్సెస్‌ని అనుమతించండి.",
    failedToFetchLocation: "స్థానాన్ని పొందడంలో విఫలమైంది.",
    pleaseEnterPetName: "దయచేసి మీ పెంపుడు జంతువు పేరును నమోదు చేయండి.",
    pleaseSelectPetSpecies: "దయచేసి మీ పెంపుడు జంతువు జాతిని ఎంచుకోండి లేదా నమోదు చేయండి.",
    pleaseEnterPetBreed: "దయచేసి మీ పెంపుడు జంతువు జాతి రకాన్ని నమోదు చేయండి.",
    pleaseSelectPetDOB: "దయచేసి మీ పెంపుడు జంతువు పుట్టిన తేదీని ఎంచుకోండి.",
    errorAddingPetTitle: "పెంపుడు జంతువును జోడించడంలో లోపం",
    monthsShort: "{months} నెలకు",
    lessThanOneMonth: "< 1 నెల",
    addPetHeaderTitle: "పెంపుడు జంతువును జోడించు",
    changePhotoBtn: "ఫోటోను మార్చండి",
    addPhotoBtn: "ఫోటోను జోడించండి",
    petNamePlaceholder: "ఉదా. మూనా",
    speciesLabel: "జాతులు",
    selectSpeciesPlaceholder: "జాతిని ఎంచుకోండి",
    customSpeciesLabel: "కస్టమ్ జాతులు",
    customSpeciesPlaceholder: "జాతి రకాన్ని నమోదు చేయండి",
    breedLabel: "జాతి రకం",
    breedPlaceholder: "ఉదా. బోర్డర్ కోలీ",
    // weightLabel: "బరువు",
    // weightPlaceholder: "ఉదా. 12",
    genderLabel: "లింగం",
    femaleGenderOption: "♀ ఆడ",
    maleGenderOption: "♂ మగ",
    dateOfBirthLabel: "పుట్టిన తేదీ",
    selectDateOfBirthPlaceholder: "పుట్టిన తేదీని ఎంచుకోండి",
    microchipIdLabel: "మైక్రోచిప్ ఐడి",
    microchipIdPlaceholder: "ఉదా. 981020000345119",
    personalityLabel: "వ్యక్తిత్వం",
    savingProgress: "సేవ్ చేస్తోంది...",
    addPetBtn: "పెంపుడు జంతువును జోడించు",
    pleaseWriteQuestionFirst: "దయచేసి మొదట మీ ప్రశ్నను వ్రాయండి.",
    failedToPostQuestionMsg: "ప్రశ్నను పోస్ట్ చేయడంలో విఫలమైంది.",
    askCommunityHeaderTitle: "కమ్యూనిటీని అడగండి",
    circleOptionalLabel: "సర్కిల్ (ఐచ్ఛికం)",
    globalCircleOption: "గ్లోబల్",
    questionLabel: "ప్రశ్న",
    questionPlaceholder: "మీ ప్రశ్న ఏమిటి?",
    detailsOptionalLabel: "వివరాలు (ఐచ్ఛికం)",
    shareMoreContextPlaceholder: "మరింత సమాచారం పంచుకోండి...",
    tagsOptionalLabel: "ట్యాగ్‌లు (ఐచ్ఛికం, కామాలతో వేరుచేయబడినవి)",
    tagsPlaceholder: "ఆరోగ్యం, పోషకాహారం, శిక్షణ",
    postQuestionBtn: "ప్రశ్నను పోస్ట్ చేయి",
    todayCelebration: "ఈరోజు! 🎉",
    tomorrowCelebration: "రేపు!",
    inDaysCelebration: "{days} రోజుల్లో",
    turningYearOld: "{age} సంవత్సరం నిండుతోంది",
    turningYearsOld: "{age} సంవత్సరాలు నిండుతున్నాయి",
    petBirthdaysHeaderTitle: "పెంపుడు జంతువుల పుట్టినరోజులు",
    upcomingCelebrationsTitle: "రాబోయే వేడుకలు",
    upcomingCelebrationsSub: "మీ పెంపుడు జంతువుల ప్రత్యేక రోజులను ట్రాక్ చేయండి మరియు సిద్ధం చేయండి!",
    noBirthdaysFoundTitle: "పుట్టినరోజులు ఏవీ కనుగొనబడలేదు",
    noBirthdaysFoundSub: "మీరు మీ పెంపుడు జంతువులను జోడించారని మరియు వాటి పుట్టిన తేదీని సెట్ చేశారని నిర్ధారించుకోండి! వాటి పుట్టినరోజులను జోడించడానికి మీరు మీ పెంపుడు జంతువుల ప్రొఫైల్‌లను సవరించవచ్చు.",
    unblockUserTitle: "@{username}ను అన్‌బ్లాక్ చేయాలా?",
    unblockUserSub: "వారు మీ ప్రొఫైల్‌ను చూడగలరు మరియు మిమ్మల్ని మళ్లీ సంప్రదించగలరు.",
    unblockActionBtn: "అన్‌బ్లాక్ చేయి",
    failedToUnblockMsg: "వినియోగదారుని అన్‌బ్లాక్ చేయడంలో విఫలమైంది.",
    blockedAccountsHeaderTitle: "బ్లాక్ చేయబడిన ఖాతాలు",
    noBlockedAccountsTitle: "బ్లాక్ చేయబడిన ఖాతాలు లేవు",
    noBlockedAccountsSub: "మీరు బ్లాక్ చేసిన వినియోగదారులు ఇక్కడ కనిపిస్తారు. మీరు వారిని ఎప్పుడైనా అన్‌బ్లాక్ చేయవచ్చు.",
    blockedAccountsCountSingle: "{count} బ్లాక్ చేయబడిన ఖాతా",
    blockedAccountsCountPlural: "{count} బ్లాక్ చేయబడిన ఖాతాలు",
    unblockBtnLabel: "అన్‌బ్లాక్",
    monShort: "సోమ",
    tueShort: "మంగళ",
    wedShort: "బుధ",
    thuShort: "గురు",
    friShort: "శుక్ర",
    satShort: "శని",
    sunShort: "ఆది",
    // bookAppointmentHeaderTitle: "అపాయింట్‌మెంట్ బుక్ చేయండి",
    vetCardShortInfo: "జనరల్ · సర్జరీ · ఇప్పుడు తెరిచి ఉంది",
    selectDateLabel: "తేదీని ఎంచుకోండి",
    selectTimeLabel: "సమయాన్ని ఎంచుకోండి",
    confirmAppointmentBtn: "అపాయింట్‌మెంట్‌ను ధృవీకరించండి",
    bookAVetLabel: "వెట్ అపాయింట్‌మెంట్ బుక్ చేయండి",
    logVaccineLabel: "టీకాను నమోదు చేయండి",
    logVitalsLabel: "వైటల్స్‌ను నమోదు చేయండి",
    logMedsLabel: "మందులను నమోదు చేయండి",
    careAndHealthHeaderTitle: "సంరక్షణ & ఆరోగ్యం",
    reminderLabel: "రిమైండర్",
    monthlyCheckupDueMsg: "ఈ వారం నెలవారీ తనిఖీ చేయాల్సి ఉంది",
    bookNowBtn: "ఇప్పుడే బుక్ చేయండి",
    careServicesLabel: "సంరక్షణ సేవలు",
    medicalRecordsTile: "వైద్య రికార్డులు",
    petPassportTile: "పెంపుడు జంతువు పాస్‌పోర్ట్",
    whosePassportQuestion: "ఎవరి పాస్‌పోర్ట్?",
    whichPetQuestion: "ఏ పెంపుడు జంతువు?",
    selectPetPassportSub: "వారి పాస్‌పోర్ట్‌ను చూడటానికి ఒక పెంపుడు జంతువును ఎంచుకోండి",
    selectPetRecordsSub: "ఆరోగ్య రికార్డులను చూడటానికి ఒక పెంపుడు జంతువును ఎంచుకోండి",
    yearsShort: "{years} సం.",
  },
};

export type TranslationKeys = keyof typeof translations.en;

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: TranslationKeys) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("en");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const savedLanguage = await AsyncStorage.getItem("furr.language");
        if (savedLanguage === "hi" || savedLanguage === "te" || savedLanguage === "en") {
          setLanguageState(savedLanguage);
        }
      } catch (error) {
        console.error("Failed to load language", error);
      } finally {
        setLoading(false);
      }
    };
    loadLanguage();
  }, []);

  const setLanguage = async (lang: Language) => {
    try {
      setLanguageState(lang);
      await AsyncStorage.setItem("furr.language", lang);
    } catch (error) {
      console.error("Failed to save language", error);
    }
  };

  const t = (key: TranslationKeys): string => {
    const translationSet = translations[language] || translations.en;
    return translationSet[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
